OE4T/meta-tegra

- classes/image_types_tegra.bbclass
The usage of ext4 with a yocto image can cause slow loading of the kernel image from
u-boot (See #42).  As a workaround, an ext3 filesystem can be used, so allow
integrators to override the default ext4 filesystem.
> image_types_tegra: allow the underlying filesystem type to be overridden

- recipes-bsp/tegra-binaries/tegra-libraries_28.1.0.bb
- recipes-graphics/drm/libdrm_2.4.75.bbappend
The alternative with the highest priority is selected. By default, the
freedesktop alternative has priotity 20, and the tegra alternative has
priority 10.
See the update-alternatives bbclass for information on how to change the
priorities
Signed-off-by: Jonatan Pålsson <jonatan.palsson@pelagicore.com>
> libdrm: Add libdrm-tegra as alternative

- recipes-kernel/linux/linux-tegra_4.4.bb
Having AUTOREV prevents yocto reproducible offline builds
based on previous downloaded sources.
This is important when releasing the sources to customer and guarantee
that
it's the same source code used in their released binaries.
Having a floating AUTOREV means less control over the source code used.
> linux-tegra_4.4.bb: Change AUTOREV to specific commit hash

- conf/machine/include/tegra210.inc
As stated in meta/classes/image_types.bbclass:7, IMAGE_ROOTFS_ALIGNMENT is in KB.
> Fix #46 by setting 4K alignment for ROOTFS

- classes/image_types_tegra.bbclass
Add all the necessary tools from ${SOC_FAMILY}-flashtools-native
to the tegraflash zip, so it can be flashed without needing the
tools available separately.
Signed-off-by: Samuli Piippo <samuli.piippo@qt.io>
> image_types_tegra: include flashtools to tegraflash package

- conf/machine/jetson-tk1.conf
- recipes-bsp/tegra-binaries/tegra-configs-alsa_21.6.0.bb
- recipes-bsp/tegra-binaries/tegra-configs_21.6.0.bb
Since commit f3c95e88 (alsa-state: update bbappend to use common tegra
override) building alsa-state on TK1 is failling because there is no
tegra-configs-alsa-21.6 package.
Update the TK1 alsa config to also use a tegra-configs-alsa package
like the other tegra platforms.
Signed-off-by: Alban Bedel <alban.bedel@avionic-design.de>
> alsa-state: add the missing tegra-configs-alsa-21.6 package

- conf/machine/include/tegra186.inc
- conf/machine/include/tegra210.inc
- recipes-bsp/tegra-binaries/libdrm-nvdc_28.2.0.bb
- recipes-bsp/tegra-binaries/libdrm-nvdc_28.2.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries_28.2.0.bb
- recipes-bsp/tegra-binaries/tegra-libraries_28.2.1.bb
- recipes-graphics/drm/libdrm-tegra-shim_git.bb
- recipes-graphics/mesa/mesa/egl-gles2-nv-extensions.patch
- recipes-graphics/mesa/mesa_%.bbappend
- recipes-graphics/wayland/egl-wayland/nvidia_wayland.json
- recipes-graphics/wayland/egl-wayland_1.1.0.bb
- recipes-graphics/wayland/eglexternalplatform_git.bb
- recipes-graphics/wayland/weston-3.0.0/0001-compositor-drm-Release-current-next-fb-when-deactiva.patch
- recipes-graphics/wayland/weston-3.0.0/0002-gl-renderer-Add-EGLDevice-enumeration-support.patch
- recipes-graphics/wayland/weston-3.0.0/0003-gl-renderer-Add-support-for-EGLDevice-composited-fra.patch
- recipes-graphics/wayland/weston-3.0.0/0004-gl-renderer-Add-EGL-client-support-for-EGLStream-fra.patch
- recipes-graphics/wayland/weston-3.0.0/0005-compositor-drm-Gracefully-handle-vblank-and-flip-inv.patch
- recipes-graphics/wayland/weston-3.0.0/0006-compositor-drm-Add-support-for-EGLDevice-EGLOutput.patch
- recipes-graphics/wayland/weston-3.0.0/0007-simple-egl-Do-not-set-EGL-up-until-XDG-setup-is-comp.patch
- recipes-graphics/wayland/weston-3.0.0/0008-compositor-Process-stream-attach-requests-with-wl_eg.patch
- recipes-graphics/wayland/weston-3.0.0/0009-Add-nvidia-release-notes-file.patch
- recipes-graphics/wayland/weston-3.0.0/0010-libweston-have-compositor-drm-try-drmOpen-should-ude.patch
- recipes-graphics/wayland/weston-3.0.0/0011-updates-to-work-with-tegra-drm-nvdc.patch
- recipes-graphics/wayland/weston-3.0.0/weston.default
- recipes-graphics/wayland/weston_3.0.0.bbappend
- recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend
- recipes-multimedia/argus/tegra-mmapi-glheaders_28.2.1.bb
See [this wiki page](https://github.com/madisongh/meta-tegra/wiki/Wayland-Weston-support-on-TX1-TX2) for more info.
Fixes #102 and #41.
> Restore libdrm, add Wayland and Weston support

- conf/machine/include/tegra124.inc
The DEFAULTTUNE assignment is unconditional and misplaced so it always
overrides the settings from the distro or local.conf. Instead it
should use the default value assignment (?=) and be placed before the
include of tune-cortexa15.inc.
Furthermore the value set is suboptimal as the tegra124 SoC support
thumb mode and vfpv4, using "cortexa15thf-neon-vfpv4" enable these two
features in the default settings.
Signed-off-by: Alban Bedel <alban.bedel@avionic-design.de>
> machine/include/tegra124.conf: Fix the DEFAULTTUNE assignment.

- recipes-bsp/tegra-binaries/gstreamer1.0-plugins-tegra_21.6.0.bb
- recipes-bsp/tegra-binaries/gstreamer1.0-plugins-tegra_21.7.0.bb
- recipes-bsp/tegra-binaries/gstreamer1.0-plugins-tegra_28.2.0.bb
- recipes-bsp/tegra-binaries/gstreamer1.0-plugins-tegra_28.2.1.bb
- recipes-bsp/tegra-binaries/libdrm-nvdc_28.2.0.bb
- recipes-bsp/tegra-binaries/libdrm-nvdc_28.2.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries_21.6.0.bb
- recipes-bsp/tegra-binaries/tegra-libraries_21.7.0.bb
- recipes-bsp/tegra-binaries/tegra-libraries_28.2.0.bb
- recipes-bsp/tegra-binaries/tegra-libraries_28.2.1.bb
- recipes-bsp/tegra-binaries/tegra-shared-libraries.inc
- recipes-bsp/tegra-binaries/xserver-xorg-video-nvidia.inc
The libraries provided by nvidia are linked against glibc, so they
can't be used in builds using another libc. To prevent the user from
finding this the hard way add a check for the libc to all the recipes
that install some .so file from nvidia.
Signed-off-by: Alban Bedel <alban.bedel@avionic-design.de>
> tegra-binaries: Make sure glibc is used with nvidia libraries

- recipes-bsp/u-boot/u-boot-tegra-common-2016.07.inc
RFS: I'm not sure if this is correct, as I don't fully understand why we are installing /boot/Image in the u-boot package. I know that this fixes the build issue I am seeing, but I don't know if it may introduce some other issue. @madisongh could you advise?
Background:
Currently, I'm seeing an RPM conflict between the kernel-image package and the u-boot-tegra package because they both install the (identical) file /boot/Image. Removing the /boot/Image installation in u-boot-tegra fixes the issue.
> RFS: u-boot-tegra /boot/Image conflict fix

- recipes-graphics/libglvnd/libglvnd/0001-Build-with-x11-or-wayland-egl.patch
- recipes-graphics/libglvnd/libglvnd_1.1.1.bb
- recipes-graphics/mesa/mesa_%.bbappend
There's not much that needed to change to enable this. There is some minor patching to libglvnd so that it doesn't try to build glx and it has a couple of typedefs that it needs. Then a minor fixup to the mesa bbappend.
I'm sending this PR to warrior since that's where I've tested it (and where I'll be using it), but I've rebased the commits to [master+no_x](/kekiefer/meta-tegra/tree/master+no_x) if you'd rather I submit that. I don't anticipate any problems.
> Use wayland with no x11 in distro features

- classes/cuda.bbclass
Add kernel-modules to CUDA run-time dependencies. Without it
CUDA 10 is not properly working and CUDA-capable devices are
NOT detected.
> cuda.bbclass: Add kernel-modules to CUDA RDEPENDS

- recipes-devtools/visionworks/libvisionworks_1.6.0.500n.bb
Attempts to build an SDK with -c populate_sdk and with libvisionworks included along with other
packages which use pkgconfig fails with:
> Error: Transaction check error:
file /usr/lib/pkgconfig from install of libvisionworks-dev-1.6.0.500n-r0.armv8a_tegra186 conflicts with file from package spdlog-dev-1.3.1-r0.aarch64
file /usr/lib/pkgconfig conflicts between attempted installs of libvisionworks-dev-1.6.0.500n-r0.armv8a_tegra186 and librealsense2-dev-2.13.0-r0.aarch64
file /usr/lib/pkgconfig conflicts between attempted installs of cuda-command-line-tools-dev-10.0.166+1-r0.armv8a_tegra186 and libvisionworks-dev-1.6.0.500n-r0.armv8a_tegra186
Solution is to use install -d for ${libdir}/pkgconfig instead of cp -R --preserve copy
> Fix transaction check errors with libvisionworks

- recipes-devtools/cmake/cmake/findcuda-dont-reset-cflags.patch
Refresh findcuda-dont-reset-cflags.patch for thud, so it doesn't hunk.
Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>
> cmake: refresh findcuda-dont-reset-cflags.patch

- recipes-multimedia/gstreamer/gstreamer1.0-omx-tegra_1.0.0-r32.2.1.bb
This removes a significant amount of build dependencies for the image I am building (based on Jetson TX2).
> gstreamer1.0-omx-tegra: remove unneeded build-dependency

- recipes-graphics/libglvnd/libglvnd/0003-Enable-build-without-X11-headers.patch
- recipes-graphics/libglvnd/libglvnd_1.2.0.bb
Preprocessor falls through in EGL/eglplatform.h to resolving a couple
typdefs using X11 headers. This works fine when the distro has X11 in
it, but is obviously a problem otherwise.
Make sure we pick up these typedefs using Wayland headers instead,
which are sure to be present.
---
For reference, here is a portion of the error this fixes:
```
| FAILED: src/25a6634@@nvidia-egl-wayland@sha/wayland-eglstream-server.c.o
| aarch64-oe-linux-gcc -march=armv8-a+crc --sysroot=/mnt/act-data/fsl/sources/poky/build-jetson-xavier/tmp/work/aarch64-oe-linux/egl-wayland/1.1.3-r0/recipe-sysroot -Isrc/25a6634@@nvidia-egl-wayland@sha -Isrc -I../git/src -I../git/include -I../git/wayland-egl -Iwayland-eglstream -I/mnt/act-data/fsl/sources/poky/build-jetson-xavier/tmp/work/aarch64-oe-linux/egl-wayland/1.1.3-r0/ …
```
> egl-wayland: fix for Wayland-only build

- contrib/recipes-devtools/gcc/gcc-7.3.inc
- contrib/recipes-devtools/gcc/gcc-common.inc
- contrib/recipes-devtools/gcc/gcc-configure-common.inc
- contrib/recipes-devtools/gcc/gcc-cross-canadian.inc
- contrib/recipes-devtools/gcc/gcc-cross-canadian_7.3.bb
- contrib/recipes-devtools/gcc/gcc-cross.inc
- contrib/recipes-devtools/gcc/gcc-cross_7.3.bb
- contrib/recipes-devtools/gcc/gcc-crosssdk.inc
- contrib/recipes-devtools/gcc/gcc-crosssdk_7.3.bb
- contrib/recipes-devtools/gcc/gcc-multilib-config.inc
- contrib/recipes-devtools/gcc/gcc-runtime.inc
- contrib/recipes-devtools/gcc/gcc-runtime_7.3.bb
- contrib/recipes-devtools/gcc/gcc-sanitizers.inc
- contrib/recipes-devtools/gcc/gcc-sanitizers_7.3.bb
- contrib/recipes-devtools/gcc/gcc-shared-source.inc
- contrib/recipes-devtools/gcc/gcc-source.inc
- contrib/recipes-devtools/gcc/gcc-target.inc
- contrib/recipes-devtools/gcc/gcc_7.3.bb
- contrib/recipes-devtools/gcc/libgcc-common.inc
- contrib/recipes-devtools/gcc/libgcc-initial.inc
- contrib/recipes-devtools/gcc/libgcc-initial_7.3.bb
- contrib/recipes-devtools/gcc/libgcc.inc
- contrib/recipes-devtools/gcc/libgcc_7.3.bb
- contrib/recipes-devtools/gcc/libgfortran.inc
- contrib/recipes-devtools/gcc/libgfortran_7.3.bb
Using .inc files for GCC 9 by GCC 7 leads to issues with missing
omp.h while building UnifiedMemoryStreams from cuda-samples.
By porting apppropriate include files from release Thud of the
Yocto Project to the contrib sub-layer these issues are avoided.
> gcc-7.3: Fix include files for GCC 7

- recipes-bsp/u-boot/u-boot-tegra-common-2016.07.inc
This is required for Mender's 'mender-persist-systemd-machine-id' feature to work properly, but in my opinion it should be added to meta-tegra so anyone using 'bootargs' will be able to use them as expected.
> Added bootargs variable to KERNEL_ARGS

- recipes-bsp/tegra-binaries/files/tegra186-flash-helper.sh
- recipes-bsp/tegra-binaries/files/tegra194-flash-helper.sh
The flash helper scripts can be used to flash the whole system, but
individual partitions can also be programmed by changing the command
sent to the recovery mode program.
This change adds a '-c' argument to the t186 and t194 flash helper
scripts.
It can be used, e.g. to program just the kernel partition:
tegra194-flash-helper.sh -c "signwrite kernel ${DEPLOY_DIR}/tegra-minimal-initramfs-jetson-xavier.cpio.gz.cboot;reboot" flash.xml.in tegra194-p2888-0001-p2822-0000.dtb jetson-xavier.cfg,jetson-xavier-override.cfg 0x9190000
Or e.g. the device tree partition:
tegra194-flash-helper.sh -c "signwrite kernel ${DEPLOY_DIR}/tegra194-p2888-0001-p2822-0000.dtb;reboot" flash.xml.in tegra194-p2888-0001-p2822-0000.dtb jetson-xavier.cfg,jetson-xavier-override.cfg 0x9190000
> tegra1xx-flash-helper.sh: add ability to set arbitrary flash command

- classes/image_types_tegra.bbclass
For Jetson TX2, the default configuration uses cboot to load
U-Boot. Script doflash.sh requires cboot.bin. If it is not
present the scripts fails with:
Error: Return value 4
This fix ensures that task do_deploy of cboot will be executed
and cboot.bin will be present even if U-Boot has been selected
as a bootloader.
> image_types_tegra.bbclass: Deploy cboot.bin

- recipes-bsp/tegra-binaries/tegra-libraries_32.2.0.bb
This currently made the tegra-libraries package depend on the tegra-libraries-argus package, because the binary would require the libraries. It was impossible to not include tegra-libraries-argus
> Properly put the nvargus-daemon in the tegra-libraries-argus package.

- recipes-bsp/tegra-binaries/files/tegra186-flash-helper.sh
It seems to me `boardrev` should be `board_version`
> fixed potential typo in tegra186-flash-helper.sh

- recipes-bsp/tegra-binaries/files/tegra186-flash-helper.sh
the "[ "$board_version" < "300" ]" statement is not properly evaluated
due to the quirky syntax of Bash.
We can either change it to double bracket or "-lt".
> fixed if statement evaluation

- conf/machine/jetson-xavier-8gb.conf
- recipes-bsp/tegra-binaries/tegra-nvpmodel_32.2.3.bb
The xavier 8gb module uses a different nvpmodel.conf than its big brother. This change installs the right version, based on a specific `MACHINEOVERRIDES` for this module.
> Correct nvpmodel support for xavier 8gb

- external/openembedded-layer/recipes-support/libusbgx/libusbgx-config.bbappend
- external/openembedded-layer/recipes-support/libusbgx/libusbgx-config/l4t-gadget-config-setup.sh
- external/openembedded-layer/recipes-support/libusbgx/libusbgx-config/l4t.schema.in
- external/openembedded-layer/recipes-support/libusbgx/libusbgx-config/usbgx-overrides.conf
- external/openembedded-layer/recipes-support/libusbgx/libusbgx/usb-gadget.target
- external/openembedded-layer/recipes-support/libusbgx/libusbgx_%.bbappend
- recipes-bsp/l4t-usb-device-mode/l4t-usb-device-mode.bb
- recipes-bsp/l4t-usb-device-mode/l4t-usb-device-mode/70-l4t-usb-gadget.network
- recipes-bsp/l4t-usb-device-mode/l4t-usb-device-mode/70-l4tbr0.network
- recipes-bsp/l4t-usb-device-mode/l4t-usb-device-mode/98-usb-gadget-tty.rules
- recipes-bsp/l4t-usb-device-mode/l4t-usb-device-mode/l4tbr0.netdev
Implement a subset of the USB device mode support provided in L4T - just the NCM and RNDIS networking gadgets and the ACM (serial tty) device.
The implementation here uses `libusbgx` from the `meta-oe` layer, so you must have that layer (or recipes for `libusbgx` and its dependencies) in your build.
For the networking support, systemd-networkd configuration files are provided.
> Add USB device mode support

- recipes-devtools/cuda/cuda-command-line-tools_10.0.326-1.bb
which should be ${baselib} so multilib builds work properly.
> cuda-command-line-tools: fix another hard-coded 'lib' use

- recipes-bsp/tools/setup-nv-boot-control_1.0.bb
When building an image with sysvinit, the final build step results in an error: "mender-tegra-bup-payload-install missing". This fix makes sure for a sysvinit build that the "setup-nv-boot-control-service" package also contains a file. Otherwise this package will not be created resulting in a failure since "mender-tegra-bup-payload-install" is in the end dependent on this package.
Signed-off-by: Boris Nagels <develop@focusware.nl>
> setup-nv-boot-control: fixed the sysvinit build

- README
- classes/nvidia_devnet_downloads.bbclass
- recipes-bsp/tegra-binaries/tegra-binaries-32.1.0.inc
- recipes-bsp/tegra-binaries/tegra186-flashtools-native_32.1.0.bb
For builds not requiring secure boot support on tegra186
platforms, skip downloading the secureboot package if
NVIDIA_DEVNET_MIRROR is not defined.
[Fixes #284]
> tegra186-flashtools-native: make NVIDIA_DEVNET_MIRROR optional

- conf/machine/jetson-xavier-8gb.conf
This was used originally to identify this machine variant in the
tegra-nvpmodel build, but the NVPMODEL variable has since been
added to the machine definition itself, so this is no longer required.
> jetson-xavier-8gb: drop unused MACHINEOVERRIDES 'xavier-8gb'

- recipes-bsp/tegra-binaries/libdrm-nvdc_32.3.1.bb
to avoid conflicts with the real libdrm's packages.
Fixes #290
> libdrm-nvdc: extend DEBIAN_NOAUTONAME to -dev, -dbg packages

- classes/image_types_tegra.bbclass
- recipes-bsp/tegra-binaries/tegra-bootfiles_32.2.3.bb
when installing into the sysroot, instead of fixing the name
based on MACHINE.  This allows for the possibility of having
multiple flash layouts apply to a single MACHINE.
> meta: use PARTITION_LAYOUT_TEMPLATE to name flash layout file

- classes/image_types_tegra.bbclass
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra186-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra210-flash-helper.sh
- recipes-bsp/u-boot/u-boot-bup-payload.bb
- recipes-kernel/kernel-bup-payload/kernel-bup-payload.bb
This patch series updates how tegraflash packages are created to include the tools and files needed to create BUP payloads from the unpacked package, including a `generate_bup_payload.sh` script to automate the payload creation.
There are related changes to the flash helper scripts.
Other changes include:
* a fix for the tegra194 helper script to better handle a null BOARDEV setting for BUP payload generation
* Extending the recipes that generate BUP payloads to deploy the kernel-only, bl-only, and any other (platform-specific) partial update payloads
* Some minor dependency cleanup
Fixes #302
> Update tegraflash packaging for BUP generation and other enhancements

- recipes-core/initrdscripts/tegra-minimal-init/init-boot.sh
When we mount the root device we used ext4 hardcoded. In this commit I changed the root file system type to inherit from the `rootfstype` kernel argument. If this fails we try to mount using the `auto` type.
> add support for rootfstype kernel param when mounting rootfs from initrd

- recipes-bsp/cboot/cboot_32.4.2.bb
I don't know if NV did something sneaky and changed the archive on us, or if you pulled a corrupted archive when you did the work, but a fresh fetch of cboot sources this morning needed a new hash. I confirmed on a different machine with a second fetch of these sources that this is indeed correct.
> cboot: update sha256 hash for 32.4.2

- recipes-bsp/cboot/cboot_32.4.2.bb
Fix the SRC_URI setting to rename the downloaded tarball to
include the version number, so we don't get conflicts when
building multiple versions using a shared downloads area.
While here, also add a 'subdir' parameter so the sources
are downloaded into an appropriately named subdirectory
under ${WORKDIR}, and set S accordingly.
And now that NVIDIA includes a LICENSE file in the
package, use that in LIC_FILES_CHKSUM instead one of
the source files.
> cboot: add version number to downloaded source tarball

- recipes-graphics/libglvnd/libglvnd_1.2.0.bb
Currently, egl-wayland is included at runtime only when the weston
compositor is used, or when egl-wayland is explicitly included in
the image. But really, the compositor doesn't need to use it -- the
compositor renders with egldevice platform or some other mechanism,
and it's the clients who need the egl-wayland platform if they want
to create a wayland egl surface. To be fair, weston does actually use
the library, but only for an optional interface.
It's not valid to assume that weston will always be the compositor,
and regardless of the compositor, clients may still need this backend.
This change puts egl-wayland in the MACHINE_EXTRA_RDEPENDS inside of
tegra-common.inc so all tegra machines will have egl-wayland if the
distro uses wayland, regardless of the compositor being used.
> tegra-common: add machine extra rdepends for egl-wayland when required

- external/openembedded-layer/recipes-support/opencv/opencv_4.3.0.bbappend
When cuda is enabled, the configuration script attempts to fetch the
headers for nvidia optical flow:
| -- NVIDIA_OPTICAL_FLOW: Download: 79c6cee80a2df9a196f20afd6b598a9810964c32.zip
| CMake Error at /path/to/tmp/work/armv8a_tegra194-oe-linux/opencv/4.3.0-r0/git/cmake/OpenCVDownload.cmake:161 (message):
|   Not going to download 79c6cee80a2df9a196f20afd6b598a9810964c32.zip
| Call Stack (most recent call first):
|   /path/to/tmp/work/armv8a_tegra194-oe-linux/opencv/4.3.0-r0/contrib/modules/cudaoptflow/CMakeLists.txt:14 (ocv_download)
This change pre-fetches the archive into the opencv download cache.
> opencv: fix configuration with nvidia optical flow

- recipes-bsp/tegra-binaries/tegra186-flashtools-native_32.4.2.bb
- recipes-bsp/tegra-binaries/tegra210-flashtools-native_32.4.2.bb
No reason to be trying to strip the supplied binaries.
> tegra{186,210}-flashtools-native: set INHIBIT_SYSROOT_STRIP

- external/openembedded-layer/recipes-support/opencv/opencv/0001-Fix-search-paths-in-FindCUDNN.cmake.patch
- external/openembedded-layer/recipes-support/opencv/opencv_4.3.0.bbappend
- recipes-devtools/cudnn/cudnn_8.0.0.145-1.bb
This required fixing cudnn installs to include the un-version-suffixed header files and static libraries, as well as a patch to OpenCV so it looks for libcudnn in the right place and uses the right header file to extract version information (due to changes in CuDNN 8.0).
> Add CuDNN support to OpenCV builds

- recipes-devtools/visionworks/libvisionworks_1.6.0.501.bb
The package VisionWorksTargets.cmake set the location to the
libvisionworks library to '/usr/lib/libvisionworks.so.1.6.0' which is
not present in the recipe.
```
/.../recipe-sysroot/usr/share/visionworks/cmake/VisionWorksTargets.cmake:64 (message):
|   The imported target "visionworks" references the file
|
|      "/.../recipe-sysroot/usr/lib/libvisionworks.so.1.6.0"
```
This add the two following files from the package 'libvisionworks_1.6.0.501_arm64.deb'
- libvisionworks.so.1.6 -> libvisionworks.so.1.6.0
- libvisionworks.so.1.6.0
As a matter of fact, the 'libvisionworks.so' redirect to 'libvisionworks.so.1.6', which is not present.
> Add libvisionworks 1.6 in FILES

- contrib/recipes-devtools/gcc-7/gcc-cross-canadian.inc
- contrib/recipes-devtools/gcc-8/gcc-cross-canadian.inc
from gcc-cross-canadian.inc.  This change was made in
commit 096fa15efbcb704451b2f38ceab36508ef64f07e in OE-Core,
and fixes missing dependencies issues during package QA
for the cross-canadian compiler package.
Fixes #354
> contrib: gcc-7, gcc-8: drop obsolete shlibs exclusion

- classes/image_types_tegra.bbclass
- recipes-bsp/tegra-binaries/tegra-helper-scripts/make-sdcard.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra186-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra210-flash-helper.sh
Make it easier to populate a data partition during flashing/SDcard creation by:
* Adding DATAFILE and IMAGE_TEGRAFLASH_DATA variables to image_types_tegra.bbclass. IMAGE_TEGRAFLASH_DATA
can be set to point to the location in the build for the data partition filesystem image. If that's set, DATAFILE should be set to the filename for the filesystem image as it will appear in the tegraflash package.
* Adding support for a `--datafile <filename>`  option on the flash helper scripts.
The helper scripts will automatically handle the extra partition when calling on the underlying NVIDIA scripts for image signing/flashing/BUP generation. Between the bbclass and the helper scripts, both eMMC and SDcard cases should be handled properly.
Use `<filename> DATAFILE </filename>` in your flash layout XML …
> Directly support data partitions in image_types_tegra and the helper scripts

- recipes-bsp/u-boot/u-boot-tegra_2020.04.bb
to pick up some additional patches ported from
NVIDIA's u-boot that haven't made it upstream.
Fixes #384
> u-boot-tegra: bump SRCREV

- recipes-bsp/tegra-binaries/gstreamer1.0-plugins-tegra_32.4.3.bb
- recipes-bsp/tegra-binaries/tegra-libraries_32.4.3.bb
- recipes-bsp/tegra-sources/tegra-sources-32.4.3.inc
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvarguscamerasrc/0001-Build-fixups.patch
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvarguscamerasrc/0002-Remove-dependencies-on-tegra-mmapi-sample-code.patch
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvarguscamerasrc_1.0.0-r32.4.3.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvv4l2camerasrc/0001-Build-fixups.patch
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvv4l2camerasrc/0002-Clean-up-compiler-warnings.patch
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvv4l2camerasrc_1.14.0-r32.4.3.bb
- recipes-multimedia/gstreamer/nvgstapps/0001-Fix-compiler-warnings.patch
- recipes-multimedia/gstreamer/nvgstapps_32.4.3.bb
Starting with L4T R32.4.x, NVIDIA provides source code for the nvarguscamerasrc and nvv4l2camerasrc gstreamer plugins.
This patch series adds recipes for those plugins so we can build them from the source code, and removes the prebuilt binary copies from the `gstreamer1.0-plugins-tegra` package.
It also adds recipes for building `nvgstplayer-1.0` and `nvgstcapture-1.0` from sources to replace the prebuilt binary copies that were being installed by the `gstreamer1.0-plugins-tegra` recipe.
> Switch to building NVIDIA gstreamer camera plugins and nvgstapps from source

- recipes-bsp/cboot/cboot_32.4.3.bb
Old version was 32.4.2 from Jetpack 4.4DP, this upgrades to 32.4.3 from
Jetpack 4.4.
The only functional change appears to be some updates for spansion 32MB
qspi flash chips to speed up erase times. It's not clear when this is
used during the normal boot process.
> cboot: update to version 32.4.3

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra186-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
Allows you to flash a single partition, e.g.:
./doflash.sh -c "write CPUBL-CFG cbo.dtb; reboot"
Regression of changes made in #205
> tegra[186|194]-flash-helper: restore ability to specify flash command

- recipes-devtools/cuda/cuda-shared-binaries-10.2.89-1.inc
Add an override for CUDA_BINARIES to nullify it for
that aarch64 builds, and reconfigure the _DEFAULT
variable settings accordingly.
Fixes #406
> cuda-shared-binaries: fix use of CUDA_BINARIES

- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.9.0/0004-Fix-build.h-generation-for-cross-builds.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.9.0.bb
Patch the makefile and update the recipe to alter how the compiled-in
build information is generated.  This should fix failures on certain
build hosts and better support reproducible builds.
Fixes #429 
> libnvidia-container-tools: fix generation of compiled-in build info

- classes/container-runtime-csv.bbclass
- external/openembedded-layer/recipes-multimedia/v4l2apps/v4l-utils_%.bbappend
The list of files in the csf for v4l-utils does not match the list
in /etc/nvidia-container-runtime/host-files-for-container.d/l4t.csv
on a Jetpack 4.4 based stock NVIDIA image.  This is problematic
for the libv4l2rds libraries when attempting to install v4l-utils
in a container.  The install works fine if the container is running
on an NVIDIA image, but when running on OE4T you see an error
message:
```
unable to make backup link of './usr/lib/aarch64-linux-gnu/libv4l2rds.so.0.0.0' before installing new version: Invalid cross-device link
```
To avoid this, add support for removing container runtime files
in the container-runtime-csv class using a glob pattern, and
use this pattern to avoid placing libv4l2rds in the container
runtime.
> Support csv file reference removal globs

- recipes-bsp/u-boot/u-boot-tegra-common-2016.07.inc
Signed-off-by: Arnstein Kleven <arnsteinkleven@gmail.com>
> Update u-boot SRCREV to include allow equal sign as key value separation patch

- recipes-devtools/deepstream/deepstream-5.0_5.0.0-1.bb
- recipes-devtools/deepstream/deepstream_5.0.0.bb
Add deepstream recipes support and deepstream docker fix
- Backport GStreamer 1.14 from warrior for deepstream docker support
- Add recipe for deepstream-5.0 (core libraries, GStreamer plugins, samples, python binding)
- Add recipe for deepstream python apps
- Add python 3.6 recipe from python 3.7 recipe as base, since deepstream python binding requires python3.6
> Deepstream Support

- classes/container-runtime-csv.bbclass
- external/openembedded-layer/recipes-multimedia/v4l2apps/v4l-utils_%.bbappend
This commit has already been merged in the `master` branch. I have cherry-picked the commit of @dwalkes to include it in the `dunfell-l4t-r32.4.3` branch as well.
The list of files in the csf for v4l-utils does not match the list
in /etc/nvidia-container-runtime/host-files-for-container.d/l4t.csv
on a Jetpack 4.4 based stock NVIDIA image.  This is problematic
for the libv4l2rds libraries when attempting to install v4l-utils
in a container.  The install works fine if the container is running
on an NVIDIA image, but when running on OE4T you see an error
message:
```
unable to make backup link of './usr/lib/aarch64-linux-gnu/libv4l2rds.so.0.0.0' before installing new version: Invalid cross-device link
```
To avoid this, add support for removing container runtime files
in the …
> Support csv file reference removal globs - dunfell-l4t-r32.4.3

- README.md
- conf/machine/jetson-nano-2gb-devkit.conf
- recipes-bsp/u-boot/u-boot-tegra_2020.07.bb
* Add a machine configuration file
* U-Boot SRCREV update with a patch from NV's downstream U-Boot repo modified for the v2020.07 code base
> Jetson Nano 2GB Devkit support

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
When running the odmsign_ext function for Xavier, NV_ARGS
must be set for the soft fuses configuration in order to generate
the rcm_2 files used during flashing.
> tegra-helper-scripts: fix generation of rcm_2 files for tegra194

- recipes-devtools/cuda/cuda-nvgraph_10.2.89-1.bb
Analysis of libnvgraph shows that libcurand and libcusolver
are NEEDED by it, so add cuda-curand and cuda-cusolver to
its build-time dependencies so the packaging code can locate
those libraries and set the runtime depenencies appropriately.
Fixes #472
> cuda-nvgraph: add DEPENDS setting

- recipes-bsp/tegra-binaries/files/0009-Update-tegraflash_internal.py-for-Python-3.9.patch
- recipes-bsp/tegra-binaries/tegra186-flashtools-native_32.4.4.bb
- recipes-bsp/tegra-binaries/tegra210-flashtools-native_32.4.4.bb
The tegraflash-internal.py script was using a function removed in python 3.9. Update patching for the script to use the new version of this function.
If preferred, I can roll this patch into the 0006 patch which does similar work.
> tegra-flashtools-native: make compatible with python 3.9

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra210-flash-helper.sh
For tegra210:
* Pass --key argument where needed
* Fix the --bct argument for secured devices
* Handle direct flashing, BUP, and SDcard generation
When signing occurs during a build, only direct flashing is
supported; no separate SDcard generation.  Since NVIDIA
doesn't actually support secure boot on the SDcard-equipped
Nano dev kits, this shouldn't have much of an impact.
For tegra194:
* Fix recognition of secured devices. 
Note, however, that when flashing secured devices without pre-signed binaries (i.e., using `-u` and possibly `-v` to specify the signing keys), one must follow the instructions in the L4T documentation and manually set `BOARDID`, `FAB`, `BOARDSKU` and `BOARDREV` in the environment when running the `doflash.sh` script, which will bypass the BR_CID check anyway.  The …
> tegra-helper-scripts: fix secureboot support in tegra210 and tegra194 helpers

- recipes-bsp/tegra-binaries/tegra-libraries_32.4.4.bb
To improve compatibility with NVIDIA's pre-built L4T
containers, we need to match the symlink that L4T uses
for the Vulkan ICD file, rather than installing the
file directly.  Otherwise, containers that are built
against stock L4T cannot be run due to a conflict
between the in-container symlink and the actual file.
Using the exact same baroque symlink mapping that
NVIDIA does, while ugly, eliminates the conflict and
makes us more compatible.
This should address the failure seen in #448
> tegra-libraries: relocate the Vulkan config file

- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvideo4linux2-1.14.0-r32.3.1/0001-v4l2videoenc-Fix-negotiation-caps-leak.patch
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvideo4linux2-1.14.0-r32.3.1/0002-v4l2allocator-Fix-data-offset-bytesused-size-validat.patch
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvideo4linux2-1.14.0-r32.3.1/0003-v4l2bufferpool-Avoid-set_flushing-warning.patch
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvideo4linux2_1.14.0-r32.3.1.bb
Backport: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/merge_requests/649
- v4l2videoenc: Fix negotiation caps leak
https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/commit/dbdbcfe7ff1b329e9ce23e5a3be6e860dc7aacec?merge_request_iid=649
- v4l2allocator: Fix data offset / bytesused size validation
https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/commit/0344c50eafa5a1b1bc203808d8950e3b07e563e8?merge_request_iid=649
- v4l2bufferpool: Avoid set_flushing warning
https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/commit/b8f1f2195ec7ef5f930a4b0bf66ce484ca21d5fa?merge_request_iid=649
This is intended to fix:
(gst-launch-1.0:4621): GStreamer-CRITICAL **: 15:51:27.489: gst_buffer_resize_range: assertion 'bufmax >= bufoffs + offset + size' failed …
> zeus-l4t-r32.3.1: Fix gst_buffer_resize_range: assertion 'bufmax >= bufoffs + offset + size' failed

- recipes-bsp/tegra-binaries/tegra-libraries_32.3.1.bb
Fix #463 [Zeus: nvv4l2h265enc: Error getting capabilities for device '/dev/nvhost-msenc']
Backport:
```
tegra-libraries: don't install libnvv4l2, libnvv4lconvert
These are not directly linked against by anything, and don't
appear to provide any functionality that isn't provided by
the open-source libv4l2 libraries, so just remove them.
```
This is needed on zeus to work properly with the gstreamer nvv4l2 plugin.
> zeus-l4t-r32.3.1: Fix nvv4l2h265enc getting capabilities for device

- classes/container-runtime-csv.bbclass
- classes/cuda.bbclass
- classes/image_types_tegra.bbclass
- conf/machine/include/tegra-common.inc
- contrib/conf/layer.conf
- external/openembedded-layer/recipes-multimedia/v4l2apps/v4l-utils_%.bbappend
- external/openembedded-layer/recipes-support/eigen/libeigen_3.3.7.bbappend
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.9.0/0004-Fix-build.h-generation-for-cross-builds.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.9.0.bb
- recipes-bsp/tegra-binaries/tegra-helper-scripts/nvflashxmlparse.py
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra210-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-libraries_32.3.1.bb
- recipes-bsp/tegra-binaries/tegra-nvphs/nvphs.service
- recipes-devtools/gie/tensorrt_6.0.1-1.bb
- recipes-graphics/libglvnd/libglvnd_1.2.0.bb
- recipes-multimedia/gstreamer/gstreamer1.0-omx-tegra_1.0.0-r32.3.1.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_%.bbappend
Port of several updates from dunfell-l4t-r32.4.3 to dunfell:
* Updates to support secure boot flashing on tegra210 and tegra194 platforms.
* Addition of `--spi-only` option for the tegra210 flash helper to simplify split SDcard burning and SPI flashing
* Fixes for gstreamer plugins, libglvnd, container support, etc.
> Dunfell backports

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra186-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra210-flash-helper.sh
This commit adds support for specifying the USB device instance to update as a new command line argument. This allows supporting multiple NVIDIA devices that may be connected simultaneously with the flash script. The command line usage is as follows:
--usb-instance <id> -- Specify the USB instance to connect to; integer ID (e.g. 0, 1), bus/dev (e.g. 003/091), or USB port path (e.g. 3-14). The latter is best.
> Add support for the USB device instance to update

- recipes-bsp/tegra-binaries/tegra-helper-scripts/make-sdcard.sh
Fixes an issue where the card may still be busy before the partprobe
sync, resulting in "partprobe failed after partitioning" failure.
Signed-off-by: Jon Magnuson <jon.magnuson@gmail.com>
---
It could have just been a fluke, but my very first attempt at running `make-sdcard` failed with:
```
About to make an SDcard image on /dev/sdh. OK? y
Init...TBC...RP1...EBT...WB0...BPF...BPF-DTB...FX...TOS...DTB...LNX...EKS...BMP...RP4...APP...[OK]
ERR: partprobe failed after partitioning /dev/sdh
```
Adding a 1s sleep and running again succeeded:
```
About to make an SDcard image on /dev/sdh. OK? y
Init...TBC...RP1...EBT...WB0...BPF...BPF-DTB...FX...TOS...DTB...LNX...EKS...BMP...RP4...APP...[OK]
Writing...TBC...RP1...EBT...WB0...BPF...TOS...DTB...LNX...EKS...BMP...RP4...APP...[OK: /dev/sdh]
```
> tegra-helper-scripts: delay before partprobe in make-sdcard

- recipes-bsp/tools/tegra-eeprom-tool_1.1.2.bb
Signed-off-by: Shlomi Vaknin <shlomi.39sd@gmail.com>
> tegra-eeprom-tool: add at24 kernel module dependency

- recipes-bsp/tools/tegra-eeprom-tool_1.2.0.bb
No new features in the tools themselves, just a refactoring
to expose a shared library for use by other tools.
> tegra-eeprom-tool: udpate to 1.2.0

- recipes-bsp/tools/tegra-boot-tools_2.0.1.bb
Replacements for the nvbootctrl and nv_update_engine
tools on tegra186/tegra194 platforms.
> tegra-boot-tools: add recipe

- classes/image_types_tegra.bbclass
to have the KERNEL_ARGS settings replace the /chosen/bootargs
property in the device tree, rather than append to it. This
was done for the other platforms, and for BUP payloads, but
was missed for Xavier tegraflash packaging.
Fixes #503
Replaces #504
> image_types_tegra.bbclass: fix bootargs setting for tegra194

- classes/cuda.bbclass
- recipes-devtools/ccache/cuda-compiler-check-native_1.0.bb
- recipes-devtools/ccache/cuda-compiler-check/cuda-compiler-check.sh
- recipes-devtools/cuda/cuda-samples_10.2.89-1.bb
For #474 
Seems to be OK with a couple of basic test builds, and doesn't appear to break non-ccache builds.  Haven't tested meson + cuda + ccache. 
One limitation is that CMake projects that use the old (and deprecated) FindCUDA module, instead of the current CUDA language support, won't be able to take advantage of ccache for nvcc compilations.  No plan to fix that.
> WIP: ccache compatibility for CUDA builds

- classes/image_types_tegra.bbclass
- recipes-bsp/tegra-binaries/tegra-helper-scripts/nvflashxmlparse.py
- recipes-bsp/tegra-binaries/tegra-redundant-boot-base_32.4.4.bb
- recipes-bsp/tegra-binaries/tegra-redundant-boot-rollback_32.4.3.bb
- recipes-bsp/tools/tegra-boot-tools_2.1.0.bb
- recipes-bsp/tools/tegra-bootpart-config_1.0.bb
- recipes-bsp/u-boot/u-boot-bup-payload.bb
- recipes-kernel/kernel-bup-payload/kernel-bup-payload.bb
* Update tegra-boot-tools to version 2.1.0, which supports tegra210 platforms for bootloader updates
* Add recipe to build the config file that tegra-boot-tools needs on tegra210 platforms
* Refactor the tegra-redundant-boot recipes to make it easier to replace the NV-provided updater tools
> tegra-boot-tools updates

- recipes-bsp/u-boot/u-boot-tegra_2020.10.bb
to 'u-boot-initial-env' so that the libubootenv tools can
find the file automatically.
Fixes #510
> u-boot-tegra: set UBOOT_INITIAL_ENV

- .github/ISSUE_TEMPLATE/meta-tegra-bug-report.md
- CONTRIBUTING.md
- README.md
As discussed in the monthly meeting, move the contributing content from https://github.com/OE4T/meta-tegra/wiki/OE4T-Contributor-Guide into a CONTRIBUTING.md
Also add a start at an issue template.
> Move contributing page into repo and add issue template

- .github/ISSUE_TEMPLATE/meta-tegra-bug-report.md
Use markdown.
Remove relative link which doesn't work and use link to README.md
getting help section instead.
Signed-off-by: Dan Walkes <danwalkes@boulderai.com>
> meta-tegra-bug-report: cleanup and fix links

- recipes-bsp/tegra-binaries/files/0009-Update-tegraflash_internal.py-for-Python-3.9.patch
- recipes-bsp/tegra-binaries/tegra186-flashtools-native_32.3.1.bb
- recipes-bsp/tegra-binaries/tegra210-flashtools-native_32.3.1.bb
methods getiterator have been removed on python 3.9.
Methods getchildren() and getiterator() of classes :class:`~xml.etree.ElementTree.ElementTree`
and :class:`~xml.etree.ElementTree.Element` in the :mod:`~xml.etree.ElementTree` module
have been removed. They were deprecated in Python 3.2.
Use iter(x) or list(x) instead of x.getchildren() and x.iter() or list(x.iter()) instead
of x.getiterator(). (Contributed by Serhiy Storchaka in :issue:`36543`.)
https://github.com/python/cpython/blob/master/Doc/whatsnew/3.9.rst
Signed-off-by: Jose Quaresma <quaresma.jose@gmail.com>
> [zeus] tegra186-flashtools-native: tegraflash_internal fix with python 3.9.

- classes/l4t_deb_pkgfeed.bbclass
- conf/layer.conf
- recipes-bsp/tegra-binaries/tegra-nvs-base_32.4.4.bb
I've tracked down a bunch of cases in my test builds where packages that could be reused between different Tegra SoCs are instead getting rebuilt or repackaged.  The patches here fix all of the issues I've been able to find so far.
> Changes to improve sstate reuse

- recipes-bsp/cboot/cboot-t18x/0007-t186-l4t.mk-make-some-build-options-configurable.patch
- recipes-bsp/cboot/cboot-t18x/0008-t186-add-bootinfo-to-build.patch
- recipes-bsp/cboot/cboot-t18x/0009-Add-machine-ID-to-kernel-command-line.patch
- recipes-bsp/cboot/cboot-t18x_32.4.4.bb
- recipes-bsp/cboot/cboot-t19x/0007-t194-l4t.mk-make-some-build-options-configurable.patch
- recipes-bsp/cboot/cboot-t19x/0008-Support-A-B-slot-for-kernel-on-SDcards-and-USB-devic.patch
- recipes-bsp/cboot/cboot-t19x/0009-tegrabl_cbo-support-A-B-slots.patch
- recipes-bsp/cboot/cboot-t19x/0010-usb_sd_boot-fix-unused-label-warning-when-extlinux-i.patch
- recipes-bsp/cboot/cboot-t19x/0011-t194-add-bootinfo-to-build.patch
- recipes-bsp/cboot/cboot-t19x/0012-Add-machine-ID-to-kernel-command-line.patch
- recipes-bsp/cboot/cboot-t19x_32.4.4.bb
- recipes-bsp/cboot/files/0001-Convert-Python-scripts-to-Python3.patch
- recipes-bsp/cboot/files/0002-macros.mk-fix-GNU-make-4.3-compatibility.patch
- recipes-bsp/cboot/files/0003-Restore-version-number-to-L4T-builds.patch
- recipes-bsp/cboot/files/0004-Fix-spurious-console-none-warning.patch
- recipes-bsp/cboot/files/0005-Add-bootinfo-module-definition-to-tegrabl_error.patch
- recipes-bsp/cboot/files/0006-Add-bootinfo-module.patch
* Refreshed and rebased existing patches
* Added module for accessing tegra-bootinfo variables from
tegra-boot-tools
* Add patch to silence a spurious warning about 'console=none'
Covers both cboot-t18x and cboot-t19x.
> cboot: add patches setting machine ID in kernel command line

- recipes-bsp/tools/tegra-boot-tools_2.2.1.bb
> tegra-boot-tools: update to 2.2.1

- recipes-kernel/linux/linux-tegra_4.9.bb
To pick up fixes for KVM support as well as patches
for recently-announced security vulnerabilities
CVE-2021-1069 and CVE-2021-1071.
> linux-tegra: bump SRCREV

- recipes-bsp/cboot/cboot-t18x_32.4.4.bb
- recipes-bsp/cboot/cboot-t19x_32.4.4.bb
- recipes-bsp/cboot/files/0000-Drop-mistaken-global-variable-definition-in-sdmmc_de.patch
A typo in a header file results in a global variable instead of
a type definitions, leading to linker failures when compiling
with gcc 10 and its defaulting to -fno-common.
> cboot: add patch for gcc-10 compilation failures

- classes/image_types_tegra.bbclass
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra186-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra186-flashtools-native_32.5.0.bb
With R32.5.0, we now have to encrypt the kernel and kernel-dtb images on tegra186 and tegra194 platforms. The encryption process is different than for the bootloader.
> Secureboot updates for 32.5.0

- classes/l4t_deb_pkgfeed.bbclass
- recipes-l4t-workarounds/tar/tar-l4t-workaround-native_1.0.bb
- recipes-l4t-workarounds/tar/tar-l4t-workaround/tar-wrapper.sh
- recipes-l4t-workarounds/zstd/zstd-l4t-workaround-native_1.4.8.bb
- recipes-l4t-workarounds/zstd/zstd-l4t-workaround/0001-Makefile-sort-all-wildcard-file-list-expansions.patch
Second attempt, targeting the correct branch this time.
Fixes #559
> Workarounds for handling zstd-compressed tarballs in L4T deb packages

- recipes-bsp/tegra-wifi/tegra-wifi_1.0.bb
Make sure tegra-wifi rules are applied before applying systemd rules.
Otherwise, systemd will use an incorrect name for the wifi interface.
Fixes #571 
Signed-off-by: Niels Avonds <niels@nobi.life>
> tegra-wifi_1.0.bb: increase udev rules priority

- classes/l4t_deb_pkgfeed.bbclass
I missed this in prior testing somehow, but the PATH= being
prepended to the command string in the bitbake fetcher's
unpack method isn't actually doing what we need it to - the
environment only changes for the first command in the string
of commands &&ed together, so the tar wrapper script wasn't
actually getting used.
So yet another workaround here, to set PATH in the environment
so from do_unpack().
Yet another fix related to #559.
> l4t_deb_pkgfeed.bbclass: one more fix for the tar/zstd issue

- conf/machine/jetson-xavier-nx-devkit.conf
Recent Xavier NX devkit modules got a version bump, so to make
sure we can build compatible BUP payloads, add that FAB to the
list of specs.
> jetson-xavier-nx-devkit: add BUP support for FAB 300

- recipes-bsp/u-boot/u-boot-tegra_2020.04.bb
so we are now based off patches-v2020.04-l4t-r32.4.3
to be aligned with L4T R32.4.3.
> u-boot-tegra: update SRCBRANCH and SRCREV

- conf/machine/jetson-tx2-devkit.conf
Jetson TX2 devkit modules got a version bump, so to make
sure that we can build compatible BUP payloads, add that FAB to the
list of specs is needed.
> jetson-tx2-devkit: add BUP support for FAB D02

- classes/image_types_tegra.bbclass
- conf/machine/include/tegra-common.inc
- conf/machine/include/tegra186.inc
- conf/machine/include/tegra210.inc
- recipes-bsp/u-boot/u-boot-tegra-bootimg.inc
- recipes-kernel/linux/linux-tegra_4.9.bb
* Fixes an issue with omitting the initramfs completely
* Cleanup for handling separate kernel + initrd
* Drop extra variable and just use INITRAMFS_IMAGE_BUNDLE to determine if we're using a bundled vs separate initramfs
For #591
> Fixes and cleanup for different kernel/initramfs combinations

- classes/l4t_deb_pkgfeed.bbclass
- recipes-devtools/cuda/cuda-samples_10.2.89-1.bb
- recipes-devtools/cudnn/cudnn_8.0.0.180-1.bb
- recipes-devtools/gie/tensorrt_7.1.3-1.bb
- recipes-graphics/l4t-graphics-demos/l4t-graphics-demos.inc
- recipes-multimedia/argus/tegra-mmapi-32.5.0.inc
Integrating VPI is presenting a problem due to the way we compose the SRC_URIs for packages coming from the L4T feeds.
Reworking the logic to calculate the download path on a per-package basis works better for VPI and some of the other L4T packages, and should be more future-proof.  This does require the addition of an L4T_DEB_GROUP setting for some of the recipes, since it's no longer set by default, but we can also drop that setting from some other recipes.
> Refinements to l4t_deb_pkgfeed.bbclass

- recipes-bsp/tegra-binaries/tegra-nvpmodel-base_32.5.1.bb
This change allows setting a variable in e.g. your machine configuration
to specify the default setting that nvpmodel will make at first boot.
If left unspecified, the default power model set by nvidia will be used,
as before.
To change the default config to 0 (MAXN), for example, you can add the
following to your machine configuration:
NVPMODEL_CONFIG_DEFAULT = "0"
> tegra-binaries: nvpmodel: support setting NVPMODEL_CONFIG_DEFAULT

- recipes-bsp/tegra-binaries/tegra-helper-scripts/make-sdcard.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
Fixes #621 by redirecting input for `tegraflash.py` to `/dev/null` so whatever it is in the NVIDIA tools that's messing with the input stream doesn't affect the terminal input, so the confirmation prompt in `make-sdcard` works again.  Only Xavier flash helper needs this, as the problem doesn't manifest itself for Nano (t210).
Also fixes a minor issue in handling unrecognized responses to the confirmation prompt in make-sdcard.
> Script fixes for SDcard creation with R32.5.x

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra186-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra210-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-redundant-boot-rollback_32.5.1.bb
* Warn on machine name longer than 31 characters
* Generate error in the flash helper script during BUP generation if the TNSPEC exceeds 63 characters
Fixes #638
> TNSPEC-related length checks

- classes/image_types_tegra.bbclass
- conf/machine/include/tegra-common.inc
- recipes-bsp/bootlogo/bootlogo-custom_1.0.bb
- recipes-bsp/bootlogo/bootlogo.inc
- recipes-bsp/cboot/cboot-t19x/0012-bmp-support-A-B-slots.patch
- recipes-bsp/cboot/cboot-t19x_32.5.0.bb
- recipes-bsp/tegra-binaries/bootlogo-prebuilt_32.5.1.bb
- recipes-bsp/tegra-binaries/tegra-bootfiles_32.5.1.bb
- recipes-bsp/tegra-binaries/tegra186-flashtools-native_32.5.1.bb
- recipes-bsp/u-boot/u-boot-bup-payload.bb
- recipes-kernel/kernel-bup-payload/kernel-bup-payload.bb
This adds support for packaging a custom bootlogo in the tegraflash package to show at boot. Leaving `PREFERRED_PROVIDER_virtual/bootlogo` set to the default `bootlogo-prebuilt` will package the default `bmp.blob`. An alternative `bootlogo-custom` recipe will use `imagemagick-native` (meta-oe) to resize an arbitrary input image and construct the blob from scratch.
Note that the boot logo is put in the deploy directory. This location is used so that updaters can leverage this artifact to handle as required. The BMP/BMP_b partitions are not part of the bootloader or kernel update payloads.
> Support customizable bootlogo blob

- external/openembedded-layer/recipes-support/opencv/opencv_4.5.%.bbappend
The required version changed upstream. Adjust recipe to fetch this
version.
> external/openembedded-layer: opencv: update opticalflow download hash

- recipes-bsp/bootlogo/bootlogo-custom_1.0.bb
The bootlogo-oe4t repo requires git-lfs, and this isn't necessarily
installed. Switching to source tarball releases takes care of this.
> bootlogo-custom: switch to source tarball release

- external/openembedded-layer/recipes-multimedia/v4l2apps/v4l-utils/0002-Replace-stat-fstat-calls-with-__xstat-__fxstat.patch
- external/openembedded-layer/recipes-multimedia/v4l2apps/v4l-utils_%.bbappend
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvideo4linux2-1.14.0-r32.5.0/0008-Replace-stat-call-with-__xstat.patch
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvideo4linux2_1.14.0-r32.5.0.bb
- recipes-multimedia/libv4l2/libv4l2-minimal/0001-Replace-stat-fstat-calls-with-__xstat-__fxstat.patch
- recipes-multimedia/libv4l2/libv4l2-minimal_1.18.0.bb
With the [upgrade of glibc to 2.33 in OE-Core](https://git.openembedded.org/openembedded-core/commit/meta/recipes-core/glibc?id=aa87638cf4f2bef66df92f961c7814f6b482fd3d), some libraries in the OS that get mapped directly into containers are making syscalls that were re-implemented in the new version, resulting in symbol failures when trying to run applications in the NGC-hosted L4T containers.
It's the `stat()` family of calls that are causing the problem, so apply patches to use an older mechanism for making those calls which is compatible with the older glibc present in the containers.
> Fixes for L4T container compatibility

- recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.9.0.bb
- recipes-containers/libnvidia-container-tools/libnvidia-container-tools_1.0.6.bb
- use protocol=https
- modprobe repo renamed master branch to 'main'
> libnvidia-container-tools: update SRC_URIs

- recipes-bsp/arm-trusted-firmware/arm-trusted-firmware.inc
- recipes-bsp/arm-trusted-firmware/arm-trusted-firmware_1.3-l4t-32.5.0.bb
- recipes-bsp/trusty/trusty-l4t.inc
Make the ATF and trusty builds more reproducible by explicitly setting build time stamps based on SOURCE_DATE_EPOCH,
and improve the version information.
> Update compiled-in build strings in TOS components

- recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.9.0.bb
added branch specification to SRC_URI of Nvidia modprobe
this is required as bitbake fails to fetch the recipe otherwise
Signed-off-by: Fabian Schaltegger fabian.schaltegger@kitro.ch
> component: libnvidia-container-tools

- classes/image_types_tegra.bbclass
- conf/machine/include/tegra210.inc
- recipes-bsp/tegra-binaries/files/0009-Remove-xxd-dependency-from-l4t_sign_image.sh.patch
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra186-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra186-flashtools-native_32.5.1.bb
Fixes for handling signing during builds (using `TEGRA_SIGNING_ARGS` to point to the key files) for all platforms.
See https://github.com/OE4T/meta-tegra/discussions/684
> In-build signing fixes

- classes/image_types_tegra.bbclass
- recipes-bsp/tegra-binaries/files/0011-Fix-missing-t186-boot-partitions-in-l4t_bup_gen.func.patch
- recipes-bsp/tegra-binaries/tegra186-flashtools-native_32.5.1.bb
- recipes-bsp/tools/tegra-boot-tools_2.3.0.bb
- recipes-bsp/tools/tegra-bootpart-config_1.0.bb
Updated tegra-boot-tools to support a complete reformatting/repartitioning/overwrite of the boot device on t186 and t194 platforms. 
Combined with an installer program/script that runs from an initrd, can be used to handle wipe-and-reinstall upgrades between L4T versions that change flash layouts by:
* reformatting and repartitioning the eMMC
* installing the new rootfs into the new partitions
* using `tegra-bootloader-upgrade --initialize` to make the system bootable
> tegra-boot-tools update

- recipes-devtools/deepstream/deepstream-5.0_5.0.0-1.bb
and a runtime dependency on libvisionworks-devso-symlink, since
that is also needed by some of the gstreamer plugins.
Fixes:  #673 #713
> deepstream-5.0: add missing .so symlinks

- conf/machine/include/agx-xavier-uefi.inc
* here is the logs from the serial UART
[serial_uart_xavier_uefi.log](https://github.com/OE4T/meta-tegra/files/6572138/serial_uart_xavier_uefi.log)
> conf/machine: enable serial uart via the micro-USB connector J501

- recipes-bsp/l4t-usb-device-mode/l4t-usb-device-mode/70-l4t-usb-gadget.network
- recipes-bsp/l4t-usb-device-mode/l4t-usb-device-mode/70-l4tbr0.network
The original config files were for use with an older version of systemd
and needed some tweaks to work with newer versions.
Also flag the links as not required for network-online, especially
since some connected hosts may try to activate both of them, but only
one will come on-line at a time.
> l4t-usb-device-mode: refresh systemd-networkd config files

- conf/machine/jetson-xavier-nx-devkit-emmc.conf
Jetson Xavier NX devkit modules got a version bump, so to make
sure that we can build compatible BUP payloads, add that FAB to the
list of specs is needed.
> jetson-xavier-nx-devkit-emmc: add BUP support for FAB 300

- conf/machine/jetson-xavier-nx-devkit-emmc.conf
This reverts commit f89a07ce91d43dbdb175d746e8c7c0292e14ff37.
No need to add FAB 300 because it's related to PCN206980 (hardware
changes in Jetson Xavier NX)
Please refer to the the document:
https://developer.nvidia.com/jetson-xavier-nx-pcn206980-dram-emmc-manufacturing-bom-expansion
Signed-off-by: Ilies CHERGUI ilies.chergui@gmail.com
> Revert "jetson-xavier-nx-devkit-emmc: add BUP support for FAB 300"

- contrib/recipes-multimedia/gstreamer-1.14/gst-plugins-package.inc
- contrib/recipes-multimedia/gstreamer-1.14/gstreamer1.0-plugins-base_1.14.4.bb
- contrib/recipes-multimedia/gstreamer-1.14/gstreamer1.0-plugins.inc
gstreamer1.0-plugins-tegra-nvcompositor RDEPENDS on libgstbadvideo-1.0,
but no providers of the package can be found.
This commit was patterned after:
https://git.openembedded.org/openembedded-core/commit/?id=d5650e00f7b26b8949ca3baad7df4b8a4ea918a7
Signed-off-by: Chad McQuillen <chad.mcquillen@lexmark.com>
> gstreamer: add libgst packages to PACKAGES_DYNAMIC

- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvideo4linux2_1.14.0-r32.5.0.bb
With GCC 10+, `-fcommon` is no longer the default. This is not a significant issue for the majority of packages, as they have been updated to reflect this change. However, nvvideo4linux2 has not, and requires this work-around to successfully build with GCC 10+.
Please let me know if this isn't the desired way to fix this issue!
> Add workaround to fix nvvideo4linux2 build

- recipes-bsp/cboot/cboot-t18x_32.5.0.bb
- recipes-bsp/cboot/cboot-t19x_32.5.0.bb
- recipes-bsp/cboot/files/0015-Fix-ext4-multi-block-linear-directory-traversal.patch
The existing code wasn't handling multi-block directories
correctly.
Fixes #751
> cboot-*: add patch for ext4 linear directory traversal

- recipes-bsp/cboot/cboot-t18x_32.5.2.bb
- recipes-bsp/cboot/cboot-t19x_32.5.2.bb
- recipes-bsp/cboot/files/0016-ext2-fix-symlink-support-in-ext2_dir_lookup.patch
ext2_dir_lookup was incorrectly using the original path string while
recursively performing a lookup on a symlink, causing cboot to crash
when trying to recursively identify the link node.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
> cboot-*: add patch to fix symlink support in ext2_dir_lookup

- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libtirpc126/0001-__rpc_dtbsize-rlim_cur-instead-of-rlim_max.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libtirpc126_1.2.6.bb
With recent systemd versions, process limits on the number of open files
have been raised by a couple of orders of magnitude (K to G). The libtirpc
library, which is unfortunately used by libnvidia-container-tools to implement
some inter-process communication, allocates some arrays of tracking structures based
on the open-files limit (e.g., dtablesze) - leading to memory allocation failures
as it tries to allocate multi-GiB arrays off the heap.
Add a modified patch, back-ported from libtirpc 1.3.2, that caps the array sizes
back down to 1K, to work around this problem for now.  The original patch only
handled the svc client; the modification also limits the array size for the
server side.
Fixes #760
> external/virtualization-layer: patch libtirpc126 to limit fd table sizes

- classes/l4t_deb_pkgfeed.bbclass
Fixed a missing update for the new override syntax. This fixes
an issue with l4t .deb packages using zstd compression not extracting
properly.
> l4t_deb_pkgfeed.bbclass: fix for new override syntax

- external/virtualization-layer/recipes-containers/nvidia-container-runtime/nvidia-container-runtime_3.1.0.bb
- external/virtualization-layer/recipes-containers/nvidia-container-toolkit/nvidia-container-toolkit_1.0.5.bb
Allow the user to select either docker-moby or docker-ce as the default
docker provider (docker.inc, used by both docker-moby and docker-ce has
the required rprovides logic for the common docker package).
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
> recipes-containers: rdepend on docker instead of docker-ce

- conf/layer.conf
- conf/machine/include/tegra-common.inc
- external/meta-python/recipes-devtools/python3-tensorrt/python3-tensorrt_8.0.1.bb
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins/0001-CMakeLists.txt-fix-cross-compilation-issues.patch
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins_8.0.1-1.bb
- recipes-devtools/deepstream/deepstream-5.1_5.1.0-1.bb
- recipes-devtools/gie/tensorrt-core_8.0.1-1.bb
- recipes-devtools/gie/tensorrt-plugins-prebuilt_8.0.1-1.bb
- recipes-devtools/gie/tensorrt-samples/0001-Makefile-fix-cross-compilation-issues.patch
- recipes-devtools/gie/tensorrt-samples_8.0.1-1.bb
- recipes-multimedia/argus/tegra-mmapi-samples_32.6.1.bb
In this PR: 
* Split tensorrt recipe to `tensorrt-core`, `tensorrt-plugins-prebuilt` and `tensorrt-samples` recipes.
* Add new recipe to build `tensorrt-plugins` from source.
* Update dependency list in recipes which depends on `tensorrt-core` and `tensorrt-plugins`.
> Build Tensorrt Plugins from source

- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins/0002-Tensorrt-fix-build-issues-when-using-protobuf-versio.patch
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins_8.0.1-1.bb
This is needed because of upgrade version of protobuf from 3.17.x to 3.18.x
in meta-openembedded
https://git.openembedded.org/meta-openembedded/commit/?id=d7d9597348534b9d93dd7ed8ef49fa2b5c33969d
For more details, deprecated version of SetTotalBytesLimit API was removed
in PR #8794 (https://github.com/protocolbuffers/protobuf/pull/8794)
> tensorrt-plugins: fix build issues when using protobuf version 3.18.x

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra210-flash-helper.sh
by omitting the path to tegraflash.py.
Signed-off-by: Chad McQuillen <chad.mcquillen@lexmark.com>
> tegra-helper-scripts: correct generation of flashcmd.txt

- recipes-multimedia/nvbufsurface/nvbufsurface-headers_6.0.0-1.bb
to align with Deepstream 6.0 from JetPack 4.6 (rev 2)
> nvbufsurface-headers: update to 6.0.0-1

- recipes-bsp/tegra-binaries/tegra-libraries-winsys_32.6.1.bb
> tegra-libraries-winsys: add missing L4T_DEB_TRANSLATED_BPN

- recipes-bsp/bootlogo/bootlogo.inc
The SOR settings in cboot apply gamma correction to the window
containing the bootlogo buffer. As such, either the window needs to
degamma the logo image, or the logo image must have a linear gamma.
This change does the latter, to keep limit the amount of patching
we're adding to cboot.
---
Note that this change only affects customizations to the bootlogo-custom recipe. The stock oe4t logo already cooks the bitmaps in a way that is compatible with cboot.
> bootlogo: use linear gamma to match nvdisp window settings in cboot

- recipes-l4t-workarounds/tar/tar-l4t-workaround/tar-wrapper.sh
bitbake fetcher used to pass '--no-same-owner -xpf <filename>' but
now passes '--extract --no-same-owner -p -f <filename>'
Wrapper script updated to handle new arguments.
> tar-l4t-workaround: fix up for current fetcher args

- external/meta-python/recipes-devtools/python3-tensorrt/python3-tensorrt/0001-Fixups-for-cross-building-in-OE.patch
Signed-off-by: Timon Gentzsch <timongentzsch@gmail.com>
> Hotfix to account for naming mismatch of get_override function

- recipes-bsp/tegra-binaries/tegra-libraries-multimedia-v4l_32.6.1.bb
- recipes-devtools/cuda/cuda-cudart_10.2.300-1.bb
The following libraries were not mounted into the docker containers:
- /usr/local/cuda-10.2/lib/libcudart.so.10.2.300
- /usr/lib/libv4l/plugins-wrapped/libv4l2_nvvidconv.so
which caused gstreamer to fail when loading plugins that depend on the libraries above.
> [tegra-libraries-multimedia-v4l / cuda-cudart] Add missing .so to nvidia docker pass-thorugh list.

- conf/machine/jetson-nano-devkit.conf
Jetson Nano devkit modules got a version bump, so to make sure that we
can build compatible BUP payloads, add that FAB to the list of specs is
needed.
> jetson-nano-devkit: add BUP support for FAB 401

- recipes-bsp/tegra-binaries/tegra-configs-alsa_32.6.1.bb
HDMI audio doesn't work with pulseaudio on the Jetson Nano devkit. This adds the missing ALSA configs.
> tegra-configs-alsa: install ALSA config files for tegra210

- recipes-kernel/linux/linux-tegra_4.9.bb
Compilation was failing with the following error:
| install: cannot stat 'arch/arm64/boot/dts/*.dtbo': No such file or directory
This change updates the for loop to use the find command to search
for device tree overlay files to install, as well as using the
KERNEL_OUTPUT_DIR variable as do install steps in kernel.bbclass
> linux-tegra: fix compilation when no dtb overlays are built

- recipes-graphics/wayland/egl-wayland_1.1.9.bb
The +3 commits following the 1.1.9 tag all relate to adding a new
wl_drm interface, but there's no actual implementation in there yet.
The issue with these commits is that they expect the (closed) EGL
driver to support EGL_EXT_device_drm_render_node which the Tegra
one does not. This is workaround-able (check the drm device, and
find the associated render node by its symlink in /dev/dri/by-path),
but there's no reason to do this right now if wl_drm isn't working
yet anyway.
If we end up at 1.1.10 (or whatever is next), have an otherwise
working wl_drm implementation, but still don't have egl driver
support for this extension, we can patch.
> egl-wayland: use exactly 1.1.9 tag

- recipes-graphics/mesa/tegra-udrm-gbm_1.0.1.bb
This version fixes an issue with scrambled output on t186 and t210
platforms, due to unsupported surface compression being used.
Fixes #932
Signed-off-by: Kurt Kiefer <kekiefer@gmail.com>
> tegra-udrm-gbm: update to 1.0.1 for fixes to t186/t210

- recipes-graphics/wayland/weston/0004-Fix-dmabuf-explicit-synchronization-for-tegra.patch
- recipes-graphics/wayland/weston_10.0.0.bbappend
Tegra's egl fence fds are compatible only with the kernel's older
android sync fence api. This patch update's weston's implementation
of zwp_linux_explicit_synchronization_v1 to use the android api
on tegra devices.
Signed-off-by: Kurt Kiefer <kekiefer@gmail.com>
> weston: fix dmabuf synchronization for tegra

- recipes-graphics/mesa/tegra-udrm-gbm_1.0.2.bb
which includes a fix for interacting with the
egl-gbm backend.
Fixes #931
> tegra-udrm-gbm: update to v1.0.2

- recipes-bsp/tegra-binaries/tegra-libraries_32.5.2.bb
- Re-flow CONTAINER_CSV_FILES for readability.
Signed-off-by: Chad McQuillen <chad.mcquillen@lexmark.com>>
> tegra-libraries:  add plugins-wrapped to CONTAINER_CSV_FILES

- conf/machine/jetson-nano-devkit-emmc.conf
Jetson Nano devkit modules got a version bump, but the eMMC devkit was
missed in that update. In order to build compatible BUP payloads, this
fab must be added.
Signed-off-by: Matt Harvey <mharvey@miovision.com>
I wasn't sure which branch to put this in, so I put it in the one we're using. If it belongs somewhere else I can put up another request. We noticed this issue because we ran into some boards with this fab.
> jetson-nano-devkit-emmc: add BUP support for FAB 401

- recipes-devtools/gie/tensorrt-core_8.4.0-1.bb
- recipes-devtools/gie/tensorrt-plugins-prebuilt_8.4.0-1.bb
- recipes-devtools/gie/tensorrt-samples.inc
- recipes-devtools/gie/tensorrt-samples_8.4.0-1.bb
- recipes-devtools/gie/tensorrt-trtexec-prebuilt_8.4.0-1.bb
* Using `Jetson xavier AGX` and running `run-tensorrt-tests`
* Here is the results:
```
[03/11/2022-14:57:03] [I] === Performance summary ===
[03/11/2022-14:57:03] [I] Throughput: 41087.7 qps
[03/11/2022-14:57:03] [I] Latency: min = 0.387207 ms, max = 0.447357 ms, mean = 0.402238 ms, median = 0.401947 ms, percentile(99%) = 0.420288 ms
[03/11/2022-14:57:03] [I] Enqueue Time: min = 0.0830078 ms, max = 0.229004 ms, mean = 0.090497 ms, median = 0.0871582 ms, percentile(99%) = 0.126099 ms
[03/11/2022-14:57:03] [I] H2D Latency: min = 0.00622559 ms, max = 0.0571899 ms, mean = 0.0104126 ms, median = 0.00952148 ms, percentile(99%) = 0.0272217 ms
[03/11/2022-14:57:03] [I] GPU Compute Time: min = 0.375977 ms, max = 0.403564 ms, mean = 0.388221 ms, median = 0.388443 ms, percentile(99%) = 0.393188 ms …
```
> Fixup for  tensorrt 

- external/qt5-layer/recipes-qt/qt5/qtbase/0001-eglfs-Newer-Nvidia-libdrm-provide-device-instead-dri.patch
- external/qt5-layer/recipes-qt/qt5/qtbase/0002-eglfs-add-a-default-framebuffer-to-NVIDIA-eglstreams.patch
- external/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
This change adds two patches to support tegra devices in qt5 with
the L4T release 32.7.1. The newer version of L4T appears to unify
the capabilities of tegra-udrm and drm-nvdc drivers in the NVIDIA's
libdrm, and this enables us to more easily support Qt using either
method, but does require some fixups.
The first patch is a backport from newer versions of Qt which will
allow the egldevice backend to function with the tegra-udrm. It is
not strictly necessary, but is nice because then users don't have
to worry about removing this driver if they want to e.g. switch
between Weston and Qt.
The second patch adds a default framebuffer to the initial calls
to libdrm to set modes and planes. The default value of -1 that was
used by Qt before wouldn't have been valid for any other platform,
and now …
> external/qt5-layer: fix egldevice backend for L4T 32.7.1

- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.9.0.bb
The latest git release adds ownership checks on the git tree when
a git command is invoked from pseudo context, so when the
makefiles are processed during the do_install task, an error is
reported.
Fix this by adding a REVISION variable setting to EXTRA_OEMAKE, and
also include a COMPILER setting to override shell callout to
extract the compiler path.
The following changes were already done to dunfell, and other
dunfell-* branches.
The original fix created by Matt Madison <matt@madison.systems>
Signed-off-by: Konstantin Selyunin <selyunin.k.v.@gmail.com>
> external/virtualization-layer: fix libnvidia-container-tools git issue

- external/qt5-layer/recipes-qt/qt5/qtbase/0002-eglfs-add-a-default-framebuffer-to-NVIDIA-eglstreams.patch
forward-port of fix to dunfell to always set mode for eglfs qt backend
> external/qt5-layer: set mode in eglfs by default

- recipes-bsp/tegra-binaries/tegra-configs/nv-l4t-bootloader-config.sh
- recipes-bsp/tegra-binaries/tegra-configs_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-redundant-boot-base_32.7.1.bb
The nv_bootloader_payload_updater tool is dependant on the
_/opt/nvidia/l4t-bootloader-config/nv-l4t-bootloader-config.sh_ being
present in the system to work. This update deploys this script as part
of a new tegra-configs-bootloader package.
Fixes #980 on the master branch
Signed-off-by: Mike Loder <mloder@miovision.com>
> Fix the nv_bootloader_payload_updater tool - Master Branch

- recipes-bsp/tegra-binaries/tegra-configs/nv-l4t-bootloader-config.sh
- recipes-bsp/tegra-binaries/tegra-configs_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-redundant-boot-base_32.7.1.bb
The nv_bootloader_payload_updater tool is dependant on the
/opt/nvidia/l4t-bootloader-config/nv-l4t-bootloader-config.sh being
present in the system to work. This update deploys this script as part
of a new tegra-configs-bootloader package.
Fixes #980 on the Dunfell branch
Signed-off-by: Mike Loder <mloder@miovision.com>
> Fix the nv_bootloader_payload_updater tool - Dunfell Branch

- classes/image_types_tegra.bbclass
This change leverages the INITRAMFS_LINK_NAME to 'dynamically' build
the image name returned from tegra_kernel_image method during tegra_flash
building.
This helps avoid build failures if a custom INITRAMFS_LINK_NAME is used
to generate a bundled kernel and ramdisk image.
By default, INITRAMFS_LINK_NAME expands to
```
INITRAMFS_LINK_NAME ?= "initramfs-${KERNEL_ARTIFACT_LINK_NAME}"
```
which would yield:
```
KERNEL_ARTIFACT_LINK_NAME ?= "${MACHINE}"
```
resulting in no change to default behavior.
Signed-off-by: Kevin Vanden Berge <kvandenberge@gmail.com>
> change: use initramfs link name for tegra_kernel_image

- recipes-bsp/tegra-binaries/tegra-libraries-camera_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-core_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-cuda_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-eglcore_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-glescore_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-glxcore_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-multimedia-utils_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-multimedia-v4l_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-multimedia_32.7.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-omx_32.7.1.bb
The tegra-libraries we all split in to their own recipes however they
conflict with the old tegra-libraries packages when upgrading. This
marks the previous package dependencies as conflicts so they are removed
on an upgrade.
Signed-off-by: Mike Loder <mloder@miovision.com>
_NOTE: I only have a PR for the Dunfell branch as I don't have a setup for the new master yocto with the updated syntax._
> Fix APT upgrade conflicts with the tegra-libraries

- recipes-kernel/linux/linux-tegra_5.10.bb
The module "mttcan" is disabled by default in linux-tegra.bb right now. I don't think it's a good idea for other kernels that derived from this bb file. If I want to let my kernel auto load `mttcan`. I must create something to remove it from blacklist. So I make this PR to enable mttcan by default. It will make this project more compatible.
> Remove "blacklist mttcan" from linux-tegra.bb

- recipes-kernel/linux/linux-tegra_4.9.bb
Upstream kernel.bbclass changed the inclusion of kernel image
artifacts from RDEPENDS to RRECOMMENDS.
Update this recipe accordingly.
Fixes #999
> linux-tegra: update packaging RDEPENDS->RRECOMMENDS

- recipes-bsp/tegra-binaries/tegra-configs-alsa_32.7.2.bb
The default asound.conf in L4T is only configured on the
Jetson Xavier NX for (card: tegra-hda-xnx, device id: 7).
Which is HDMI Audio Out. One can't hear audio over DP
unless the alsa config is updated to
(card: tegra-hda-xnx, device id: 3).
Commit:
-  Allows for default L4T provided alsa config to
be overridden
- Adds in a custom alsa config that configures
audio over both DP and HDMI. Only for machines
jetson-xavier-nx-devkit-{emmc}
Signed-off-by: Vincent Davis Jr <vince@underview.tech>
> tegra-configs-alsa: enable default ALSA config overrides

- recipes-bsp/tegra-binaries/tegra-bootfiles_32.7.2.bb
Fix for build dependency error caused by https://github.com/openembedded/openembedded-core/commit/6f28420ab0e8f2ab5eb06326024777a40aded0a6
> tegra-bootfiles: update RDEPENDS -> RRECOMMENDS

- conf/machine/include/devkit-wifi.inc
- conf/machine/include/xavier-nx.inc
- conf/machine/jetson-agx-orin-devkit.conf
- conf/machine/jetson-xavier-nx-devkit-emmc.conf
- conf/machine/jetson-xavier-nx-devkit.conf
Similar to the xavier nx devkit, the agx orin devkit includes a
rtl8822ce m.2 pcie wifi+bluetooth radio.
This change adds by default the necessary bits to enable it.
Signed-off-by: Kurt Kiefer <kekiefer@gmail.com>
> jetson-agx-orin-devkit: include wifi support by default

- conf/machine/jetson-nano-devkit.conf
Add new fab number to TEGRA_BUPGEN_SPECS in order to support mender
updates on newer boards.
Suggested-by: Matt Madison <matt@madison.systems>
Signed-off-by: Bartosz Golaszewski <brgl@bgdev.pl>
> machine: jetson-nano-devkit: add new fab

- recipes-devtools/vpi/libnvvpi2_2.1.6.bb
This is needed for letting the dynamic linker able to find the Nvidia
VPI library
> libnvvpi2: add pkg_postinst to create a symlink of vpi2.conf file

- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nveglgles/0002-Fix-builds-without-x11.patch
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nveglgles_1.2.3-r35.1.0.bb
Wayland only builds won't have the x11 header files, so only pick
up this header if we expect to have it.
> gstreamer1.0-plugins-nveglgles: fix builds without x11

- conf/machine/include/tegra-common.inc
Using a weak default for that it is very sensitive and not take effect
in distros that uses other types.
Setting the IMAGE_FSTYPES with a weak default can also introduce circular
dependencies because the tegraflash is lost when something is set in
IMAGE_FSTYPES and adding this again using an append in disto config
add circular dependencies for example in tegra-espimage.
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>
> tegra-common: always add tegraflash as it is the most used image

- recipes-bsp/cboot/cboot-l4t.inc
- recipes-bsp/cboot/nvdisp-init/0001-Drop-mistaken-global-variable-definition-in-sdmmc_de.patch
- recipes-bsp/cboot/nvdisp-init/0002-Convert-Python-scripts-to-Python3.patch
- recipes-bsp/cboot/nvdisp-init/0003-macros.mk-fix-GNU-make-4.3-compatibility.patch
- recipes-bsp/cboot/nvdisp-init/0004-Restore-version-number-to-L4T-builds.patch
- recipes-bsp/cboot/nvdisp-init/0005-nvdisp-init.patch
- recipes-bsp/cboot/nvdisp-init_32.7.2.bb
- recipes-bsp/uefi/edk2-firmware-tegra_35.1.0.bb
nvdisp-init is a pre-loader that is glued on before the efi firmware to set up a graphical framebuffer on t194 platforms. It's distributed as a patch to the previously released version of cboot, and a prebuilt binary.
This change adds a recipe to build nvdisp-init from source, and uses it by default for the edk2-firmware-tegra source build. The prebuilt efi binaries use the prebuilt nvdisp-init binary from the jetpack release.
> Build nvdisp-init from source

- recipes-graphics/mesa/mesa_%.bbappend
egl-gbm is required to use gbm along with egl on tegra devices.
This was an rdep on weston, but other generic gbm clients (like
kmscube) that want to use egl will need it as well. It's not
strictly required to make gbm itself work, but not being able to
initialize egl without it would be a common and unexpected surprise.
If a tegra platform is pulling in mesa to get libgbm, include this.
> mesa: libgbm: add rdepends on egl-gbm

- external/meta-python/recipes-devtools/python3-tensorrt/python3-tensorrt/0001-Fixups-for-cross-building-in-OE.patch
Fixes #1054 by restoring a missing additional patch.
> external/meta-python: restore missing patch for python3-tensorrt

- recipes-bsp/uefi/edk2-firmware-tegra_35.1.0.bb
> edk2-firmware-tegra: depends on nvdisp-init only for tegra194 SOC

- external/openembedded-layer/recipes-extended/haveged/haveged/haveged.service
- external/openembedded-layer/recipes-extended/haveged/haveged_%.bbappend
Upstream meta-oe dropped the systemd service since it is no longer
needed in Linux kernel > 5.6. But we are still on 4.9.y so we need it.
Based on https://raw.githubusercontent.com/jirka-h/haveged/v1.9.14/init.d/service.redhat
Signed-off-by: Tim Orling <tim.orling@konsulko.com>
> haveged: reintroduce systemd service

- recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.sh.in
This change replaces the use of XDG_RUNTIME_DIR as the location for
mktemp's TMPDIR with the RUNTIME_DIRECTORY variable. When run as a
user unit, RUNTIME_DIRECTORY will be set to XDG_RUNTIME_DIR, or when
run as a system unit, it will be set to /run, or as defined according
to the RuntimeDirectory variable in the unit file. When unset, mktemp
will use /tmp
> setup-nv-boot-control: use RUNTIME_DIRECTORY to fix use in system unit

- conf/machine/include/tegra-common.inc
- recipes-bsp/tegra-binaries/tegra-redundant-boot-base_35.1.0.bb
- recipes-bsp/tegra-bup-payload/tegra-bup-payload_1.0.bb
Refactor the packaging the redundant-boot recipes, so we can include the `nv_update_verifier` service in all builds.
Fixes #1071
> Add nv_update_verifier to all builds

- classes/image_types_tegra.bbclass
- recipes-bsp/uefi/l4t-launcher-extlinux.bb
This set of changes accommodate out-of-tree device tree binaries generated by a provider of `virtual/dtb`. Overall, this enables consumers of meta-tegra to generate the main kernel dtbs and dtbos, as well as the dtbos that can be used by EFI, without patching the linux-tegra or EDK2 sources.
The approach was derived from conventions set forth in the meta `devicetree` bbclass and its handling by the `kernel-fitimage` class. The assumption is that these device tree binaries will be placed under the `${DEPLOYDIR}/devicetree` location during deploy, or in `/boot/devicetree` on install. These paths are not variable in the `devicetree` bbclass, and as such are not variable here, and their contents simply globbed.
To enable building a dtb that referenced nvidia's overlayed kernel device tree …
> Support virtual/dtb provider for out-of-tree dtb/dtbo

- recipes-bsp/uefi/edk2-firmware-tegra/0001-Fix-eeprom-customer-part-numbers.patch
- recipes-bsp/uefi/edk2-firmware-tegra_35.1.0.bb
The logic in edk2-firmware-tegra's eeprom handling logic suffers a few oversights regarding customer part numbers addressed here.
First, the eeprom parsing didn't match the old cboot in terms of not requiring initialization of the length field in the eeprom. Existing hardware may not have this field set properly, so we check if it is zero and bypass the length check for this case.
Second, customer part numbers with the leading 0xcc were not being handled properly. This change fixes the addition of these parts to the /chosen/ids node, as well as fixes the handling of these parts for for comparison in the overlay logic.
> edk2-firmware-tegra: fix eeprom customer part number handling

- external/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
The previous commit has a back porting problem. The version of qtbase needs 2 patches.
Signed-off-by: Claus Stovgaard <clst@ambu.com>
> qtbase: Fix correct SRC_URI for patches in kirkstone

- recipes-multimedia/argus/tegra-mmapi-samples/0010-samples-apply-fix-for-encoder-unit-test.patch
- recipes-multimedia/argus/tegra-mmapi-samples_35.1.0.bb
which fixes a problem with its buffer management. See: https://forums.developer.nvidia.com/t/jetson-multimedia-api-35-1-0-encoder-unit-test-sample-failure/229588
Fixes #1059
> tegra-mmapi-samples: add patch for encoder unit test sample

- recipes-bsp/uefi/edk2-firmware-tegra_35.1.0.bb
Missed updating the SRCREV for the nvidia-non-osi repo when updating from R34.1.0 to R35.1.0, so we were getting an older, incompatible version of the prebuilt NvGop driver.
Fixes #1055
> edk2-firmware-tegra: update SRCREV for edk2-nvidia-non-osi

- classes/image_types_tegra.bbclass
Allow the user to replace the standard TEGRA_ESP_IMAGE image by not depending on the respective do_image_complete task.
The preferred image can be set via IMAGE_TEGRAFLASH_ESPIMG, after setting TEGRA_ESP_IMAGE to empty.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
> image_types_tegra.bbclass: allow TEGRA_ESP_IMAGE to be empty

- recipes-bsp/uefi/edk2-firmware-tegra_35.1.0.bb
Add needed extra space before adding Proprietary.
Bug noticed when generating SPDX data for the recipe.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
> edk2-firmware-tegra: fix LICENSE append

- recipes-devtools/cuda/cuda-libraries_11.4.14-1.bb
libcudla is only provided by NVidia for the target. Excluding it from the cuda-libraries-native package resolves the following compilation error:
Nothing RPROVIDES 'libcudla-native'
Signed-off-by: Enguerrand de Ribaucourt <enguerrand.de-ribaucourt@savoirfairelinux.com>
Fixes #1105
> cuda-libraries: remove libcudla from native

- recipes-bsp/tegra-binaries/gstreamer1.0-plugins-tegra-binaryonly_35.1.0.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvcompositor/0002-Skip-map-frame-in-pad-prepare-to-fix-spurious-warnin.patch
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvcompositor_1.20.5-r35.1.0.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-tegra_1.14.0-r35.1.0.bb
nvcompositor emits a spurious warning message for every frame that goes through it. This typically goes unnoticed until GST_DEBUG is at least at the warn level, but besides being annoying it is doing unnecessary work.
This PR patches the nvcompositor to skip the extraneous mapping call, and sets up the gstreamer1.0-plugins-tegra collection to use the source build of the nvcompositor.
> Source builds of nvcompositor

- recipes-bsp/tegra-binaries/tegra-redundant-boot/nv_update_verifier.init
- recipes-bsp/tegra-binaries/tegra-redundant-boot/nv_update_verifier.service
- recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.init.in
- recipes-security/optee/optee-client_3.16.0-l4t-r35.1.0.bb
* Fix the installation of the optee supplicant init script to match the INITSCRIPT_NAME
* Drop the wait on the kernel partition for `nv_update_verifier`
Fixes #1110
> Fixes for sysvinit-based startup issues

- recipes-devtools/cuda/cuda-target-environment_1.0.bb
A small spelling error - E.g. CUDA_ARCHITECTURE vs CUDA_ARCHITECTURES Without this fix the exported CUDA_ARCHITECTURES environment variable is blank, and you can see it in the cuda_target.sh
Signed-off-by: Claus Stovgaard <claus.stovgaard@gmail.com>
> cuda-target-environment: Set CUDA_ARCHITECTURES correct

- recipes-bsp/tegra-binaries/tegra-libraries-glxcore_35.1.0.bb
This fixes Vulkan support with X11 (tested with `vulkaninfo` tool in addition to other Vulkan-enabled apps).
> libglvnd: add libxcb-glx runtime dependency

- conf/machine/include/tegra210.inc
- conf/machine/jetson-agx-xavier-devkit.conf
- conf/machine/jetson-nano-2gb-devkit.conf
- conf/machine/jetson-nano-devkit-emmc.conf
- conf/machine/jetson-nano-devkit.conf
- conf/machine/jetson-tx1-devkit.conf
- conf/machine/jetson-tx2-devkit.conf
- conf/machine/jetson-xavier-nx-devkit-emmc.conf
- conf/machine/jetson-xavier-nx-devkit.conf
- recipes-bsp/tegra-binaries/tegra-nv-boot-control-config_32.7.2.bb
- recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.init.in
- recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.service.in
- recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.sh.in
- recipes-bsp/tools/tegra-boot-tools_3.1.0.bb
- recipes-bsp/tools/tegra-boot-tools_git.bb
This is already present in the JetPack 5/R35.1.0-based branches, but was more involved for R32.7.x because:
* More platforms are involved
* tegra-boot-tools also needed updating
When using the stock NVIDIA bootloader update tools, the `setup-nv-boot-control` service will add a COMPATIBLE_SPEC line to the configuration file so that BUP payload entries either matching the actual TNSPEC or the compatible spec will be considered valid for an update.  The new version of the `tegra-bootloader-update` tool implements similar logic for its compatibility checks.
With the above changes, the `TEGRA_BUP_SPECS` settings for all machines needed revising.  In most cases, fewer specs are required, making BUP packages smaller and taking less time to build/sign.
For reviewing, I'd appreciate it if someone …
> Adding COMPATIBLE_SPEC support for BUP payloads

- recipes-bsp/uefi/edk2-firmware-tegra_35.2.1.bb
nvdisp-init is needed for tegra194 soc family to pick it up from the images deploy directory.So, introducing dependency to edk2-firmware-tegra:do_compile task fixes build issue.
> edk2-firmware-tegra: update recipe for L4T R35.2.1

- recipes-graphics/mesa/tegra-udrm-gbm_1.1.0.bb
This update is required due to the removal of nvgbm in 35.2.1. It replaces the nvgbm wrapper with its own buffer allocation using nvbuffersurface.
> tegra-udrm-gbm: update to version 1.1.0

- recipes-bsp/uefi/edk2-firmware-tegra-35.2.1.inc
- recipes-bsp/uefi/files/0001-Fix-eeprom-customer-part-numbers.patch
In the port of this patch, the customer prefix was erroneously dropped from the population of customer board ids in the chosen devicetree node:
2888-0004-400 0123-123
Should read as:
2888-0004-400 ABCD-0123-123
The master branch of edk2-firmware contains a rewritten version that works correctly, so update to this version. A PR for update to 35.2.1 happened upstream around the time of the release:
https://github.com/NVIDIA/edk2-nvidia/pull/34
> edk2-firmware-tegra: fix patch for customer eeprom handling

- recipes-bsp/tegra-binaries/tegra-uefi-prebuilt_35.2.1.bb
> tegra-uefi-prebuilt: fix typo in do_compile

- conf/machine/jetson-nano-2gb-devkit.conf
- conf/machine/jetson-nano-devkit.conf
When adding support for booting from external devices, the composition of the KERNEL_ROOTSPEC setting got refactored so that the Nano and 2GB Nano dev kits no longer needed to override the full setting. I forgot about that when updating the Nano machine configs, and just copy-pasted the old setting to the new KERNEL_ROOTSPEC_DEFAULT variable. Fix that so the setting includes just the device name, like it's supposed to.
Fixes #1198
> conf/machine: fix KERNEL_ROOTSPEC_DEFAULT for SDcard-based Nanos

- recipes-bsp/tegra-binaries/tegra-helper-scripts/find-jetson-usb.sh
Currently, the `find-jetson-usb` script only looks for one level of usb devices, which doesn't let you use a usb hub
all the devices are symlinked automatically to the top level directory under `/sys/bus/usb/devices`, so we can just look at those to support direct connections and usb hubs
Not sure if this the right branch to target
> Update find-jetson-usb.sh to support usb hubs

- recipes-bsp/uefi/edk2-firmware-tegra-35.2.1.inc
- recipes-bsp/uefi/files/0005-Use-bfd-linker.patch
Build fails if using gold linker with DISTRO_FEATURE ld-is-gold. Add compiler flags to always use bfd linker.
> edk2-firmware-tegra: use bfd linker

- recipes-core/initrdscripts/tegra-flash-reboot/reboot-recovery.c
```
| /build/tmp/work/armv8a_tegra-lmp-linux/tegra-flash-reboot/1.0-r0/reboot-recovery.c:8:15: error: call to undeclared function 'syscall'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
|         return (int) syscall(SYS_reboot, LINUX_REBOOT_MAGIC1, LINUX_REBOOT_MAGIC2, LINUX_REBOOT_CMD_RESTART2, arg);
|                      ^
```
> tegra-flash-reboot: fix build with clang 16

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra234-flash-helper.sh
- recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.sh.in
Add changes to support manual [UEFI Capsule Updates](https://docs.nvidia.com/jetson/archives/r35.2.1/DeveloperGuide/text/SD/Bootloader/UpdateAndRedundancy.html#manually-trigger-the-capsule-update) in Jetpack 5.1.  This includes:
* Modifying efi variables to match stock L4T
* Modifying bup specs to match stock L4T
Tested with the sequence below and a manually generated capsule update.  The next step will be to automatically generate this capsule update as a part of the build.
Create the capsule update directory on the target:
```
mkdir -p /opt/nvidia/esp/EFI/UpdateCapsule/
```
Then on the host machine, from `~/nvidia_sdk/JetPack_5.1_Linux_JETSON_AGX_XAVIER_TARGETS/Linux_for_Tegra`, run
```
./generate_capsule/l4t_generate_soc_capsule.sh -i ~/<path to your build …
```
> uefi: capsule updates support

- recipes-bsp/tegra-binaries/files/0015-tegrasign_v3_internal-overlay.patch
- recipes-bsp/tegra-binaries/tegra-flashtools-native_35.2.1.bb
This applies the secureboot_overlay_35.2.1.tbz2 update to the signing tools that enables secure boot on Orin platforms.
> tegra-flashtools-native: apply secureboot overlay

- recipes-bsp/tegra-binaries/tegra-flashtools-native_35.2.1.bb
This fixes an issue where the tegrasign_v3_oemkey.yaml file was not being installed by the existing 'tegrasign_v3*py' install rule.
> tegra-flashtools-native: install tegrasign_v3* files

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/make-sdcard.sh
Disable automount feature on OS is not longer required.
> initrd-flash: fix auto mount trouble

- recipes-bsp/uefi/edk2-firmware-tegra-35.3.1.inc
- recipes-bsp/uefi/files/0006-fix-ensure-termination-of-TnSpec-variables.patch
As noted in the gitter channel at [1] TnSpec variables are missing termination.
This fixes issues with capsule update on at least the Xavier NX EMMC target as detailed in [2]
See related PR at [3].
1: https://matrix.to/#/!YBfWVpJwNVtkmqVCPS:gitter.im/$lhvcFxWhHn8Vi6404bqMJACJmjZ9p2DNmma7M8Mc4zk?via=gitter.im&via=matrix.org&via=3dvisionlabs.com
2: https://matrix.to/#/!YBfWVpJwNVtkmqVCPS:gitter.im/$LYaDS0zElgwnqxLbMJesGOMWO35aoI7Xonp8e5eL57A?via=gitter.im&via=matrix.org&via=3dvisionlabs.com
3: https://github.com/NVIDIA/edk2-nvidia/pull/37
> edk2-firmware-tegra: add tnspec variables patch

- recipes-bsp/tegra-binaries/tegra-libraries-multimedia-ds_35.3.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-multimedia-utils_35.3.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries-multimedia_35.3.1.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvarguscamerasrc_1.0.0-r35.3.1.bb
Creates a new recipe to install the `libnvdsbufferpool.so` library so that the main `tegra-libraries-multimedia` recipe doesn't have to depend on `gstreamer1.0-plugins-base`.
Fixes #1243
> Refactor tegra-libraries-multimedia

- recipes-bsp/tegra-binaries/tegra-pinmux-dts2cfg_35.3.1.bb
Can be used to convert the dtsi files comming from nvidia excel sheet to cfg files used later by flashvars / minimal initramfs.
On your local bsp layer you can create a recipe like this for a single machine. Just use it as inspiration
```
DESCRIPTION = "pinmux - xxxx"
DEPENDS = "tegra-pinmux-dts2cfg-native"
COMPATIBLE_MACHINE = "xxxx"
PACKAGE_ARCH = "${MACHINE_ARCH}"
SRC_URI = "path-to-your-git-repo-with-excel-and-dtsi-files"
SRCREV = "xyz"
S = "${WORKDIR}/git"
B = "${WORKDIR}/build"
do_configure[noexec] = "1"
do_compile() {
python3 ${RECIPE_SYSROOT_NATIVE}${bindir}/pinmux-dts2cfg.py \
--pinmux \
${RECIPE_SYSROOT_NATIVE}${datadir}/tegra-pinmux/addr_info.txt \
${RECIPE_SYSROOT_NATIVE}${datadir}/tegra-pinmux/gpio_addr_info.txt \
${RECIPE_SYSROOT_NATIVE}${datadir}/tegra-pinmux/por_val.txt \ …
```
> Add tegra-pinmux-dts2cfg for xavier

- recipes-bsp/tegra-binaries/tegra-helper-scripts/make-sdcard.sh
Fix the make_partitions function in make-sdcard so that it honors the partition type GUID value coming from the flash layout for any partition, not just the final one.
This fixes an issue with the ESP partition not getting recognized by UEFI as the boot partition.
> tegra-helper-scripts: fix partition type setting in make-sdcard script

- recipes-bsp/tools/tegra-boot-tools.inc
- recipes-bsp/tools/tegra-boot-tools_3.1.0.bb
- recipes-bsp/tools/tegra-boot-tools_3.1.1.bb
- recipes-bsp/tools/tegra-boot-tools_git.bb
* Refactors common settings out of the main and `_git` recipes into a `.inc` file
* Update to [3.1.1](https://github.com/OE4T/tegra-boot-tools/releases/tag/v3.1.1)
> [kirkstone-l4t-r32.7.x] update tegra-boot-tools: 3.1.0 -> 3.1.1

- classes/image_types_tegra.bbclass
- recipes-kernel/kernel-bup-payload/kernel-bup-payload.bb
Backport of the following PR https://github.com/OE4T/meta-tegra/pull/1088 onto kirkstone-32.7.x branch:
---
image_types_tegra: add support for virtual/dtb provider
This change adds support (adapted from kernel-fitimage handling) for out-of-tree device tree binary generation. It looks for a provider of virtual/dtb, and if this exists, enables the copying of device tree binaries generated by this recipe.
Signed-off-by: Kurt Kiefer [kurt.kiefer@arthrex.com](mailto:kurt.kiefer@arthrex.com)
> Backport virtual/dtb for kirkstone-32.7.x

- classes/image_types_tegra.bbclass
- recipes-kernel/kernel-bup-payload/kernel-bup-payload.bb
- bbclass and tegra-bup-payload recipe naming convention must match.
> Fix naming convention of bup payload

- recipes-bsp/tegra-binaries/tegra-nvpmodel/nvpmodel.service
- recipes-bsp/tegra-binaries/tegra-nvpmodel_35.3.1.bb
- recipes-bsp/tegra-binaries/tegra-nvpower/nvpower.service
Fixes for the `nvpower` and `nvpmodel` systemd service units so they execute only once and in the correct sequence at boot time.  Particularly on Orin Nano and NX modules, the GPU driver is very sensitive to when the power settings need to be applied via sysfs.  Errors occur if the settings are applied too early, or if nvpower hasn't performed some of the scheduling-related setup that has to be in place, or if settings are applied multiple times.
> nvpower and nvpmodel startup fixes

- conf/machine/jetson-orin-nano-devkit-nvme.conf
- conf/machine/p3509-a02-p3767-0000.conf
- conf/machine/p3768-0000-p3767-0000.conf
- conf/machine/p3768-0000-p3767-0004.conf
> Update partition layout settings for Orin Nano/NX modules

- recipes-devtools/gcc-for-nvcc/gcc-8-common.inc
Upstream commit
https://git.yoctoproject.org/poky/commit/?id=a2bf83842a72c3dfe24a824c650a2f64d3fdf1b0 added "-mbranch-protection=standard" to TUNE_CCARGS that breaks the gcc-for-nvcc (GCC 8) build during configure of libgcc-8:
configure:3731: error: in .../libgcc': configure:3734: error: cannot compute suffix of object files: cannot compile
Take this flag out of TUNE_CCARGS
Fixes #1302
> gcc-for-nvcc: fix breakage in libgcc-8 with upstream TUNE_CCARGS change

- classes/cuda.bbclass
to remove a flag added in OE-Core from compilations for CUDA targets that use an older compiler (through nvcc) which doesn't understand the new flag.
Fixes #1302
> cuda.bbclass: filter TUNE_CCARGS for CUDA builds

- classes/tegra-bup.bbclass
- conf/machine/jetson-xavier-nx-devkit-emmc.conf
- recipes-bsp/tegra-bup-payload/tegra-bup-payload_1.0.bb
- recipes-bsp/tools/setup-nv-boot-control/oe4t-set-uefi-OSIndications
- recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.sh.in
- recipes-bsp/tools/setup-nv-boot-control/uefi_common.func.in
- recipes-bsp/tools/setup-nv-boot-control_1.0.bb
- recipes-bsp/uefi/edk2-basetools-tegra-native_35.3.1.bb
- recipes-bsp/uefi/edk2-firmware-core-tegra-35.3.1.inc
- recipes-bsp/uefi/edk2-firmware-tegra-35.3.1.inc
- recipes-bsp/uefi/tegra-uefi-capsules_35.3.1.bb
Consider this just a starting point to spur some discussion on how best to implement.
1.  Should the capsules be included in the rootfs by default or simply be deployed to `${DEPLOYDIR}`?  I initially went ahead and included them in the rootfs.  That follows the pattern of how `swupdate` works (which is what we use) in `tegra-test-distro` whereby `tegra-bootloader-update` and `bl_update_payload` are packaged into the rootfs and then swupdate mounts the just programmed inactive partition to drive the bootloader upddate.  Having said that, I believe when we implemented `dm-verity` to create a full chain of trust from the bootloaders to the rootfs it created a cycle of dependencies in the build.  To break the cycle we pulled the bootloader payload out of the rootfs and packaged it directly …
> Add support for building capsules

- recipes-bsp/tools/setup-nv-boot-control/uefi_common.func.in
After working on getting `swupdate` to work I noticed that the `setup-nv-boot-control` service was failing on startup.  I shouldn't have used `[]`'s around the `efivar` command to check to see whether the variable already existed or not.
> uefi_common.func.in: fix efi variable existence check

- recipes-multimedia/gstreamer/libgstnvcustomhelper_35.4.1.bb
* This PR fixes the following issue 
```
(gst-plugin-scanner:947): GStreamer-WARNING **: 08:26:59.581: Failed to load plugin '/usr/lib/gstreamer-1.0/deepstream/libnvdsgst_nvmultiurisrcbin.so': libgstnvcustomhelper.so: cannot open shared object fi
le: No such file or directory
** (gst-plugin-scanner:947): CRITICAL **: 08:26:59.605: Couldn't g_module_open libpython. Reason: /usr/lib/libpython3.11.so: cannot open shared object file: No such file or directory
(gst-plugin-scanner:947): GStreamer-WARNING **: 08:26:59.714: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstnvvideo4linux2.so': libgstnvcustomhelper.so: cannot open shared object file: No such file o
r directory
```
> libgstnvcustomhelper: fix runtime dependency

- recipes-devtools/vpi/libnvvpi2_2.3.9.bb
* This PR fixes the following issue 
```
[ 1027.619635] pva 16000000.pva0: Direct firmware load for pva_auth_allowlist failed with error -2
[ 1027.619864] pva 16000000.pva0: looking for firmware in subdirectory
[ 1027.627758] pva 16000000.pva0: Direct firmware load for tegra19x/pva_auth_allowlist failed with error -2
[ 1027.627974] pva 16000000.pva0: failed to get firmware
[ 1027.628076] pva 16000000.pva0: pva_auth_allow_list_parse: Failed to load the allow list
```
> libnvvpi2: rename vpi2_pva_auth_allowlist firmware

- recipes-bsp/tegra-binaries/libdrm-nvdc_35.3.1.bb
This is needed to avoid spdx from failing with:
ERROR: libdrm-nvdc-35.3.1-20230319081403-r0 do_create_spdx: The recipe libdrm-nvdc is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
/home/qt/work/build/build/tmp/deploy/spdx/armv8a_tegra/packages/libdrm-lic.spdx.json
(matched in manifest-armv8a_tegra-libdrm.create_spdx)
Please verify which recipe should provide the above files.
> libdrm-nvdc: set DEBIAN_NOAUTONAME also for license package

- recipes-devtools/cuda/cuda-target-environment_1.0.bb
to filter the -mbranch-protection flag from TARGET_CC_ARCH when forming the -Xcompiler arguments in the CUDAFLAGS environment variable.
Fixes #1338
> cuda-target-environment: update arch_flags function

- external/sota/recipes-bsp/uefi/edk2-firmware-tegra/0001-L4TLauncher-boot-syslinux-instead-of-extlinux-for-os.patch
- external/sota/recipes-bsp/uefi/edk2-firmware-tegra/0002-l4tlauncher-support-booting-otaroot-based-partitions.patch
- external/sota/recipes-bsp/uefi/edk2-firmware-tegra/0003-l4tlauncher-disable-a-b-rootfs-validation.patch
- external/sota/recipes-bsp/uefi/edk2-firmware-tegra_%.bbappend
This group of patches is only applied with the sota override
that is provided by the meta-updater [1] layer
[1] https://github.com/uptane/meta-updater
> edk2-firmware-tegra: adds ostree support

- external/openembedded-layer/recipes-extended/haveged/haveged/haveged.init
- external/openembedded-layer/recipes-extended/haveged/haveged/haveged.service
- external/openembedded-layer/recipes-extended/haveged/haveged_%.bbappend
- recipes-bsp/tegra-binaries/tegra-nvphs/nvphs.service
- recipes-bsp/tegra-binaries/tegra-nvphs_32.7.4.bb
- recipes-bsp/tegra-binaries/tegra-nvpmodel/nvpmodel.service
- recipes-bsp/tegra-binaries/tegra-nvpmodel_32.7.4.bb
* Refresh the haveged bbappend so the daemon gets started when using sysvinit, and gets started earlier when using systemd.
* Update the nvpmodel and nvphs services/initscripts to ensure they start in the correct order.
Fixes #1364
> haveged, nvpmodel, and nvphs updates

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra234-flash-helper.sh
Comparing to the logic in the L4T scripts, we were missing a check that the board SKU isn't 0005 before seeing if the pinmux and PMC config files need to be overridden based on the chip SKU and FAB values.
Fixes #1365
> tegra-helper-scripts: fix AGX Orin 64GB handling in t234 helper

- classes/image_types_cboot.bbclass
- classes/image_types_tegra.bbclass
- classes/tegra-uefi-signing.bbclass
- conf/machine/include/tegra-common.inc
- recipes-bsp/tegra-binaries/tegra-uefi-prebuilt_35.4.1.bb
- recipes-bsp/uefi/edk2-firmware-tegra_35.4.1.bb
- recipes-bsp/uefi/l4t-launcher-extlinux.bb
- recipes-kernel/linux/linux-tegra_5.10.bb
@madisongh , I wanted to get this up for early feedback.  I discussed this at a high level in the last (September) OE4T monthly meeting.  I'm starting to work now on getting `digsigserver` to support UEFI signing of various artifacts.  My desire was to try and start simple (Orin NX development module fused with development keys, Orin Nano devkit carrier board, tegra-demo-distro build) and work my way up to supporting our own custom carrier card, tegra build, and production keys.  I refactored how the UEFI signing worked with the intent of making it easier for others to follow the same path.  My approach was to try and corral all the `TEGRA_UEFI_DB_KEY` and `TEGRA_UEFI_DB_CERT` references spread out in various recipes and bring those back to the `tegra-uefi-signing.bbclass`.  Then one can …
> Incorporate signing server support into tegra-demo-distro

- external/qt6-layer/recipes-qt/qt6/qtbase_%.bbappend
Add separate bbappends for Qt 6 (https://code.qt.io/cgit/yocto/meta-qt6.git). Enable the EGLFS EGLDevice platform support needed for NVIDIA boards. Disable GBM for qtbase, otherwise Qt tries to use wrong eglfs backend.
> Add support for Qt 6

- classes/tegra-uefi-capsule-signing.bbclass
- recipes-bsp/uefi/tegra-uefi-capsules_35.4.1.bb
- Move the capsule signing logic to a class in preparation for supporting capsule signing via a signing server in a means similar to tegra-uefi-signing.
> uefi: refactor uefi capsule signing

- recipes-bsp/uefi/tegra-uefi-capsules_35.4.1.bb
- The signing server version of the class that signs uefi capsules has some task dependencies that must be met.
> tegra-uefi-capsule: add TEGRA_UEFI_CAPSULE_SIGNING_EXTRA_DEPS

- recipes-devtools/cuda/cuda-target-environment_1.0.bb
Update the CUDACXXARCHFLAGS environment variable to include the same glibc 2.38 workaround to SDKs that was added to cuda.bbclass with 52f994fbb3844e11919139a4250a2859fa153ace.
Fixes #1443
> cuda-target-environment: add nvcc/glibc 2.38 workaround

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- Pre-signed builds need to ensure that DTB_FILE has been substituted with the actual kernel .dtb file in initrd-flash.xml.  Unsigned builds take a different path through initrd-flash such that the tegraXXX-flash-helper will have already made the substitution.
- Fixes #1452
> initrd-flash.sh: ensure substitution for DTB_FILE

- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins/0001-CMakeLists.txt-fix-cross-compilation-issues.patch
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins/0002-fix-build-issues.patch
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins_8.5.2.bb
Due to updates to protobuf and gcc, make some updates to the build. Namely, this means using C++17 as required by protobuf and making sure we link to the system protobuf.
Applicable to master and nanbield
> external/openembedded-layer: tensorrt-plugins: fixes for new protobuf

- external/virtualization-layer/recipes-containers/libnvidia-container/libnvidia-container_1.10.0.bb
Fixes:
```
root@jetson-agx-xavier-devkit:~# nvidia-container-cli -d log info
nvidia-container-cli: initialization error: driver error: failed to process request
root@jetson-agx-xavier-devkit:~# cat log
-- WARNING, the following logs are for debugging purposes only --
I0116 15:56:51.761083 1362 nvc.c:281] initializing library context (version=0.11.0+jetpack, build=1b60893021cd00c87f201d11eb207215afa3ab11)
I0116 15:56:51.761474 1362 nvc.c:255] using root /
I0116 15:56:51.761547 1362 nvc.c:256] using ldcache /etc/ld.so.cache
I0116 15:56:51.761618 1362 nvc.c:257] using unprivileged user 65534:65534
I0116 15:56:51.762404 1363 driver.c:134] starting driver service
E0116 15:56:51.763612 1363 driver.c:196] could not start driver service: load library failed: libcuda.so.1: cannot open shared …
```
> libnvidia-container: rdepend on tegra-libraries-cuda

- recipes-bsp/tegra-binaries/tegra-storage-layout_35.4.1.bb
When using a rootfs with external device too large for the emmc and a redundant rootfs partition, the APP_b partition is not removed from the emmc partition and therefore bup payload creation fails when it tries to place the too large rootfs into the emmc.
Expand the existing logic to remove the APP_b partition, if it exists, in addition to the APP partition.
Tested with `jetson-xavier-nx-devkit-emmc` with nvme and this config:
```
TNSPEC_BOOTDEV = "nvme0n1p1"
TEGRA_EXTERNAL_DEVICE_SECTORS = "488397168"
USE_REDUNDANT_FLASH_LAYOUT_DEFAULT = "1"
ROOTFSPART_SIZE = "59055800320"
```
After boot I see a 51GB rootfs
```
root@jetson-xavier-nx-devkit-emmc:~# df -h | grep nvme
/dev/nvme0n1p1           51.3G    720.3M     47.8G   1% /
```
Closes https://github.com/OE4T/meta-tegra/issues/1439
> tegra-storage-layout: fix support for large rootfs

- external/virtualization-layer/recipes-containers/nvidia-container-toolkit/nvidia-container-toolkit_1.11.0.bb
This feature enables the display of the version information for the `nvidia-container-toolkit` binaries. After this change, the binary versioning will appear as follows:
```bash
nvidia-container-runtime --version
NVIDIA Container Runtime version 1.11.0
commit: 670+d9de4a0
.
.
.
```
> nvidia-container-toolkit: Add version and gitCommit to nvidia-container-runtime --version

- recipes-bsp/tools/setup-nv-boot-control/uefi_common.func.in
This fixed UEFI Capsules for me with an Orin AGX with this boardspec.
```
$ tegra-boardspec 
3701-500-0005-M.0-1-0
```
> uefi_common.func.in: Fix gen_compat_3701 typo

- conf/machine/jetson-agx-xavier-devkit.conf
The 401 fab was added in dunfell-l4t-r32.5.0 but missing in this branch
> AGX Xavier missing fab

- recipes-bsp/tools/setup-nv-boot-control/uefi_common.func.in
The stock TEGRA_BUPGEN_SPECS are unchanged (supporting only fabs 400 and 402), so this is not changed here.
However, for the emmc efi variable workarounds we need to look for these fabs when applicable. Notably missing from this workaround was the listed 402 fab, the apparently new 401 fab, and also the industrial 600 fab, all of which need this workaround. So this is now all boardid=2888 configurations.
Also handled here is the gen_compat_spec. This was changed a bit to apply the workarounds for older know board skus, and leave the newer style for all unlisted fabs.
---
I have one doubt, and that is the original code only named the 400 fab. Obviously it needs the 4xx fabs moving forward. I don't know about the industrial/600 fab - is it correct that this doesn't use a spi flash and would …
> setup-nv-boot-control: support t194 p2888 fabs 401 and 402

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra-flash-helper.sh
In L4T R35.3.1, NVIDIA changed the tegraflash scripts to modify the kernel DTB used during RCM booting to disable the rtcpu node in the device tree on t19x platforms. It does so without making a new copy of the DTB file, which leads to the modified DTB getting written to the kernel-dtb partition when using initrd-flash to flash a Xavier device (in some cases).
Work around this in the helper scripts by copying the kernel DTB to a new file used only for RCM booting.
Fixes #1537
> tegra-helper-scripts: use separate kernel DTB for RCM booting on t19x

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- recipes-core/initrdscripts/tegra-flash-init/init-extra.sh
- recipes-core/initrdscripts/tegra-flash-init/init-flash.sh
- recipes-core/initrdscripts/tegra-flash-init_1.0.bb
This makes it possible for extra custom steps to take before the final reboot step of the initrd flashing process.
> initrd-flash: Add custom extra init

- conf/machine/p3768-0000-p3767-0001.conf
It seems official SDK manager is loading different BPFDTB for Orin NX 8Gb.
Also SKU is set 0001 as otherwise 0000 is used from included 16Gb Orin NX variant.
> p3768-0000-p3767-0001: allign machine config with stock SDK

- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins_8.5.2.bb
Previously the 17 standard was needed just for some plugins, and leaving 14 was fine for the rest of the project. With recent changes to absl, now we need the 17 standard for other parts as well.
This change builds on the do_configure:prepend sed fixup to include the CMakeLists.txt CMAKE_CXX_STANDARD being forced in a couple more places.
> external/openembedded-layer: tensorrt-plugins: use CMAKE_CXX_STANDARD 17

- conf/machine/p3768-0000-p3767-0001.conf
Board SKU fix was not picked for r36.3.0 branch.
So far this version seems to works fine for me.
> p3768-0000-p3767-0001: set correct SKU for Orin NX 8Gb

- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-target.inc
- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc_10.3.bb
* Kindly see below the build and package issues
1- Build issue 
```
| aarch64-oe4t-linux-g++  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/media/m2/tegra-demo-distro/build-testdistro/tmp/work/armv8a-oe4t-linux/gcc-for-nvcc/10.3.0/recipe-sysroot  -I../../../../../../work-shared/gcc-10.3.0-r0/gcc-10.3.0/libcpp -I. -I../../../../../../work-shared/gcc-10.3.0-r0/gcc-10.3.0/libcpp/../include -I../../../../../../work-shared/gcc-10.3.0-r0/gcc-10.3.0/libcpp/include  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=/media/m2/tegra-demo-distro/build-testdistro/tmp/work-shared/gcc-10.3.0-r0/gcc-10.3.0=/usr/src/debug/gcc-for-nvcc/10.3.0 …
```
> gcc-for-nvcc: fix build and package issue

- recipes-bsp/uefi/tegra-uefi-capsules_35.5.0.bb
The collection of dtb overlays used during tegraflash package creation can come from sources other than l4t or the kernel. Most commonly this is the virtual/dtb package, but it can be overridden, and is specified by the DTB_EXTRA_DEPS variable.
The migration from creating bup payloads to creating only capsules inadvertantly dropped this dependency, so this change adds it back.
> tegra-uefi-capsules: add missing DTB_EXTRA_DEPS dependency

- recipes-bsp/uefi/tegra-uefi-capsules_36.3.0.bb
Install capsules to rootfs only when TEGRA_UEFI_CAPSULE_INSTALL_DIR is set.
> tegra-uefi-capsules: conditionally install capsules

- classes-recipe/image_types_tegra.bbclass
- recipes-bsp/uefi/tegra-uefi-capsules_36.3.0.bb
Remove unnecessary dependency between firmware BUP and EFI system partition image. This creates circular dependency if you want to place your kerneln on ESP.
> remove extra esp dependency

- recipes-core/initrdscripts/tegra-flash-init/program-boot-device.sh
- recipes-core/initrdscripts/tegra-flash-init_1.0.bb
On custom board the QSPI flash can be under different name (like mtd1). Allow user to specify a device name by creating an environment file in bbappend.
> tegra-flash-init: allow user to override script variables

- recipes-bsp/uefi/tegra-uefi-capsules_36.3.0.bb
* Add missing dependency on virtual/bootloader:do_deploy, needed for all platforms
* Add missing dependency, and staging, for the ESP image, needed for the AGX Orin platform using internal storage, to satisfy the NVIDIA flashing tools while generating the BUP/capsule contents.
Fixes #1597
> tegra-uefi-capsules: add missing dependencies and setup

- recipes-bsp/uefi/edk2-firmware-tegra-35.5.0.inc
- recipes-bsp/uefi/files/0004-Ext4Pkg-Advertise-CSUM_SEED-as-supported.patch
e2fsprogs recipe in openembedded-core, updated in mickeldore release to 1.74 [1], generates (using mke2fs) ext4 partitions with "metadata_csum_seed" and  "orphan_file" features enabled by default.
Current version of Ext4Dxe driver in edk2-platforms has a bug, that prevents mounting correctly filesystems with "medata_csum_seed" enabled. This patch backports a fix from edk2-platforms upstream [2] which addresses the issue.
[1] https://e2fsprogs.sourceforge.net/e2fsprogs-release.html#1.47.1
[2] https://github.com/NVIDIA/edk2-platforms/commit/92479808e7227017cdfb19815605bb1fa877d19f
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
> bsp: edk2: apply fix for CSUM_SEED handling in Ext4Dxe

- conf/machine/include/tegra-common.inc
- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot-dtb_36.3.0.bb
- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot_36.3.0.bb
Small updates that re-enable the use of a separate virtual/dtb provider for r36. Now we can simply change the `KERNEL_DEVICETREE` variable and update the `PREFERRED_PROVIDER_virtual/dtb`. The actual recipe to build the devicetrees has to pull in the oot-modules sources to build them, so an update to tegra demo distro will be subsequently due.
> Support separate virtual/dtb provider

- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot/0001-tegra-virt-alt-Remove-leading-from-include-path-from.patch
- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot_36.3.0.bb
buildpaths is a QA warning up until now, but there are patches in oe-core/master-next which will elevate it to an error, therefore fix the error by helping makefile to not add extra leading '/', other fix would be to add another expression to -fdebug-prefix-map option in CFLAGS, but this if ok, is a better way to handle it.
> nvidia-kernel-oot: Fix buildpaths QA messages

- recipes-l4t-workarounds/tar/tar-l4t-workaround-native_1.0.bb
Fixes
WARNING: tar-l4t-workaround-native-1.0-r0 do_unpack: tar-l4t-workaround-native: the directory ${WORKDIR}/${BP} (/mnt/b/yoe/master/build/tmp/work/x86_64-linux/tar-l4t-workaround-native/1.0/tar-l4t-workaround-1.0) pointed to by the S variable doesn't exist - please set S within the recipe to point to where the source has been unpacked to
> tar-l4t-workaround-native: Switch away from S = WORKDIR

- recipes-bsp/tegra-binaries/tegra-libraries-eglcore_36.3.0.bb
And force the creation, otherwise O_P_M update does not work and fails like below
Configuring tegra-libraries-eglcore.
ln: failed to create hard link '/usr/lib/aarch64-linux-gnu/tegra-egl/libEGL_nvidia.so.0': File exists error: pkg_run_script: package "tegra-libraries-eglcore" postinst script returned status 1.
> tegra-libraries-eglcore: Create a symlink instead of hardlink

- classes/container-runtime-csv.bbclass
- classes/l4t_bsp.bbclass
- classes/l4t_deb_pkgfeed.bbclass
- external/openembedded-layer/recipes-multimedia/v4l2apps/v4l-utils_%.bbappend
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.10.0/0006-Add-support-for-separate-pass-through-tree.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.10.0.bb
- recipes-bsp/tegra-binaries/gstreamer1.0-plugins-tegra-binaryonly_32.7.5.bb
- recipes-bsp/tegra-binaries/tegra-container-passthrough_32.7.5.bb
- recipes-multimedia/gstreamer/gstreamer1.0-omx-tegra_1.0.0-r32.7.5.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvarguscamerasrc_1.0.0-r32.7.5.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvcompositor.inc
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvdrmvideosink_1.14.0-r32.7.5.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nveglgles_1.2.3-r32.7.5.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvjpeg_1.14.0-r32.7.5.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvtee_1.14.0-r32.7.5.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvv4l2camerasrc_1.14.0-r32.7.5.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvidconv.inc
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvideo4linux2_1.14.0-r32.7.5.bb
- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvvideosinks_1.14.0-r32.7.5.bb
- recipes-multimedia/libv4l2/libv4l2-minimal_1.18.0.bb
- recipes-multimedia/libv4l2/libv4l2-nvvidconv-wrapper_git.bb
Backport of https://github.com/OE4T/meta-tegra/pull/1194
Since the csv is not an static file but rather automatically generated, we need to come up with some mechanism of replacing the lib path. That's why I added CONTAINER_CSV_LIB_PATH.
But I am open to any suggestion.
> Kirkstone l4t r32.7.x+backport fix glibc conflicts in containers

- recipes-devtools/cuda/cuda-samples_git.bb
Add needed dependencies and linker flags as well as copy the data files to target, needed to run c++11_cuda sample, in order to run this the limitation is that one must be in /usr/bin/cuda-samples subdir when executing this sample, so it can find warandpeace.txt under ./data dir
> cuda-samples: Build all samples under 0_Introduction

- recipes-bsp/tegra-binaries/tegra-libraries-camera_32.7.5.bb
Add nvargis_nvraw utility, useful for debugging, getting raw data and listing sensors:
```bash
$ nvargus_nvraw --lps
nvargus_nvraw version 1.11.0
Number of supported sensor entries 5
Entry  Source Mode      Uniquename             Resolution   FR  BitDepth  Mode
Index  Index  Index                                             CSI Dyn   Type
0      0      0         imx334_front_framos   3864x2180   59  10  10    Bayer       
1      0      1         imx334_front_framos   1920x1080  120  10  10    Bayer       
2      0      2         imx334_front_framos   1944x1080   59  12  12    Bayer       
3      0      3         imx334_front_framos   3864x2180   59  12  12    Bayer       
4      0      4         imx334_front_framos   1920x1080  120  12  12    Bayer    
```
> Add nvargus_nvraw into Kirkstone l4t r32.7.x

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- When secure boot is enabled the resulting doflash.sh contains 'uefi_jetson_with_dtb_aligned_blob_w_bin_sigheader_encrypt.bin.signed' vs 'uefi_jetson_with_dtb_sigheader_encrypt.bin.signed' when secure boot is not enabled.  Update the sed command to work with both.
- The command to replace '_aligned_blob_w_bin' with '' must appear before the command to replace 'uefi_jetson' with 'rcmboot_uefi_jetson'.
> initrd-flash.sh: fix sed command when using SBK

- recipes-bsp/tegra-binaries/nvidia-l4t-optee_36.3.0.bb
`nv-tee-supplicant.service` requires script present in `/etc/systemd/nv-tee-supplicant.sh`
```
#
#
#
#
#
[Unit]
Description=OP-TEE Client Supplicant
DefaultDependencies=no
Conflicts=shutdown.target
After=systemd-modules-load.service
Before=sysinit.target shutdown.target
[Service]
Type=simple
ExecStart=/etc/systemd/nv-tee-supplicant.sh
Restart=always
RestartSec=10s
```
> nvidia-l4t-optee: install missing tee-supplicant script

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- recipes-core/initrdscripts/tegra-flash-init/init-extra-pre-wipe.sh
- recipes-core/initrdscripts/tegra-flash-init/init-flash.sh
- recipes-core/initrdscripts/tegra-flash-init_1.0.bb
This introduces a hook to the initrd-flash script which makes it possible to run custom scripts before erasing the storage disk via "erase-nvme" or overwriting it via "export-devices".
Note: There exists already an "extra" hock to run future scripts before the final reboot step. Similar to that, any future recipe intended to add custom extra pre-wipe scripts can use the TEGRA_INITRD_FLASH_INSTALL variable in the distro config to add the new package(s).
Furthermore, note that these custom scripts will need to be installed with executable permission set in the
/init_extra-pre-wipe.d folder of the tegraflash initrd image.
> initrd-flash: Add custom extra-pre-wipe

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- recipes-core/initrdscripts/tegra-flash-init/init-extra-pre-wipe.sh
- recipes-core/initrdscripts/tegra-flash-init/init-flash.sh
- recipes-core/initrdscripts/tegra-flash-init_1.0.bb
This introduces a hook to the initrd-flash script which makes it possible to run custom scripts before erasing the storage disk via "erase-nvme" or overwriting it via "export-devices".
Note: There exists already an "extra" hock to run future scripts before the final reboot step. Similar to that, any future recipe intended to add custom extra pre-wipe scripts can use the TEGRA_INITRD_FLASH_INSTALL variable in the distro config to add the new package(s).
Furthermore, note that these custom scripts will need to be installed with executable permission set in the
/init_extra-pre-wipe.d folder of the tegraflash initrd image.
> [scarthgap] initrd-flash: Add custom extra-pre-wipe

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- recipes-core/initrdscripts/tegra-flash-init/init-extra-pre-wipe.sh
- recipes-core/initrdscripts/tegra-flash-init/init-flash.sh
- recipes-core/initrdscripts/tegra-flash-init_1.0.bb
This introduces a hook to the initrd-flash script which makes it possible to run custom scripts before erasing the storage disk via "erase-nvme" or overwriting it via "export-devices".
Note: There exists already an "extra" hock to run future scripts before the final reboot step. Similar to that, any future recipe intended to add custom extra pre-wipe scripts can use the TEGRA_INITRD_FLASH_INSTALL variable in the distro config to add the new package(s).
Furthermore, note that these custom scripts will need to be installed with executable permission set in the
/init_extra-pre-wipe.d folder of the tegraflash initrd image.
> [scarthgap-l4t-r35.x] initrd-flash: Add custom extra-pre-wipe

- classes-recipe/image_types_cboot.bbclass
- recipes-kernel/linux/linux-tegra_5.10.bb
This change permits passing kernel command line arguments that include quoted strings, including dyndbg.  Without single quotes, the recipe silently produces incorrect results in such cases.
> [scarthgap-l4t-r35.x] linux-tegra: properly quote KERNEL_ARGS

- recipes-bsp/tegra-binaries/tegra-flashtools-native_36.3.0.bb
Requesting comments regarding the fix for this error (not sure it's the right way of fixing the issue): [do_image_tegraflash.log](https://github.com/user-attachments/files/16623960/do_image_tegraflash.log)
It seems when defining `TEGRA_SIGNING_ARGS = "-u path/to/pkc.key -v path/to/sbk.key"`, we get the errors when building an image.
```
[...]
| ./tegraflash.py --chip 0x23 --bl uefi_jetson_with_dtb.bin --sdram_config tegra234-p3767-0001-sdram-l4t.dts --odmdata gbe-uphy-config-8,hsstp-lane-map-3,hsio-uphy-config-0 --applet mb1_t234_prod.bin --cmd "sign"  --skipuid --cfg flash.xml --bct_backup --boot_chain A --uphy tegra234-mb1-bct-uphylane-si.dtsi --minratchet_config tegra234-mb1-bct-ratchet-p3767-0000.dts --device_config tegra234-mb1-bct-device-p3767-0000.dts --misc_config …
```
> RFC: image_types_tegra: fix depends when TEGRA_SIGNING_ARGS is defined

- recipes-devtools/cuda/cuda-sanitizer_12.2.140-1.bb
CUDA 12 added 32-bit x86 tools and libraries to the cuda-sanitizer package. They're not likely needed in our builds or SDKs, so just remove them to avoid packaging issues.
Fixes #1662
> cuda-sanitizer: remove 32-bit x86 binaries

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- recipes-core/initrdscripts/tegra-flash-init/init-extra-pre-wipe.sh
- recipes-core/initrdscripts/tegra-flash-init/init-flash.sh
- recipes-core/initrdscripts/tegra-flash-init_1.0.bb
This introduces a hook to the initrd-flash script which makes it possible to run custom scripts before erasing the storage disk via "erase-nvme" or overwriting it via "export-devices".
Note: There exists already an "extra" hock to run future scripts before the final reboot step. Similar to that, any future recipe intended to add custom extra pre-wipe scripts can use the TEGRA_INITRD_FLASH_INSTALL variable in the distro config to add the new package(s).
Furthermore, note that these custom scripts will need to be installed with executable permission set in the
/init_extra-pre-wipe.d folder of the tegraflash initrd image.
> [kirkstone] initrd-flash: Add custom extra-pre-wipe

- recipes-bsp/tegra-binaries/tegra-storage-layout-base_36.3.0.bb
Fix typo and missing 'T' character in variable reference for `PARTITION_LAYOUT_EXTERNAL`.
The current typo means if the name of the file referenced by `PARTITION_FILE_EXTERNAL` was different than the name `PARTITION_LAYOUT_EXTERNAL`, the wrong filename would be used in the l4t-storage-layout dir.
Relates to  https://github.com/OE4T/meta-tegra/pull/1684
> tegra-storage-layout-base: fix typo on external layout

- recipes-core/initrdscripts/tegra-flash-init/init-flash.sh
When a device is enumerated by the host, its usb configuration state changes to positively identify that it is ready to go. Conversely, when it is powered down, its configuration state indicates that it is no longer in that ready ('configured') state.
A side effect of the power saving for the USB peripheral would change the device into a suspended state if it is not configured, but this mechanism does not work reliably on the Orin AGX devkit.
Additionally, the gadget device sysfs node changed from a single /UDC/device/gadget function to /UDC/device/gadget.# in kernels newer than the current L4T 5.15, breaking the previous method for newer kernels.
Use this more direct method of determining if the usb host is using the device so it will work across various platforms as well as kernel …
> tegra-flash-init: use usb configuration state for connection status

- classes-recipe/image_types_tegra.bbclass
- recipes-bsp/uefi/tegra-uefi-capsules_36.3.0.bb
```
Remove ESP image dependency for BUP generation. This helps
to avoid some circular dependencies in such cases as explained in [1].
The helper script (l4t_bup_gen.func) for BUP generation doesn't use it,
and the only mention of ESP partition is in the list of boot artifacts to
be included into BUP image (bup_type=bl),
where ESP image is explicitly marked to be skipped:
5. SKIP: 0 - built in BUP, 1 - not built in BUP
t23x_bl_table=(
#PART_NAME        IMAGE_SIGNED BOARD_SPECIFIC OP_MODE_SPECIFIC SKIP
'BCT              1            1              1                0'
'BCT_A            1            1              1                0'
'BCT_B            1            1              1                0'
'BCT-boot-chain_backup 1       1              1                0'
'A_mb1            1 …
```
> tegra-uefi-capsules: remove ESP image dependency for BUP

- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot_36.3.0.bb
When using devtool, the first bitibake build after the devtool workspace is set up triggers re-execution of our do_unpack postfunc, which is overwriting the patched copy of the top-level makefile.
Avoid this by copying it in only if the top-level makefile isn't already there.
Fixes #1704
> nvidia-kernel-oot: conditionalize Makefile copying for do_unpack

- classes-recipe/image_types_tegra.bbclass
- recipes-bsp/uefi/tegra-uefi-keys-dtb.bb
I believe updating UEFI keys via tegra-uefi-keys-dtb.bb does not work on scarthgap nor master branches.
When adding UefiUpdateSecurityKeys.dts to tegra-uefi-keys-dtb.bbappend, the UefiUpdateSecurityKeys.dtbo is not installed in the sysroot of the recipe, causing tegra_bootcontrol_overlay_list() to not append it to the list of overlays to use for the capsule update. The result is that it is missing from the capsule update, making it impossible to update the KEK and other keys used by UEFI secure boot.
The problem can be observed without deploying the capsule update by searching for 'UefiUpdateSecurityKeys.dtbo' in 'tmp/work/horizon_orin_devkit-mdt-linux\tegra-uefi-capsules'; you should see that with the current code the file is not present.
With the changes proposed …
> UefiUpdateSecurityKeys.dtbo now included in capsule update.

- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot_36.3.0.bb
This pull request adds the following features:
Revision 2
########
This pull request adds the following features:
* Allow NVIDIA Kernel OOT headers to be staged, so that the users can import NVIDIA Tegra headers after defining the dependency on this package. These headers are added to the `nvidia-kernel-oot-dev` package.
Testing:
* The NVIDIA Kernel OOT headers are successfully staged in the recipe sysroot of recipes that DEPENDS on `nvidia-kernel-oot`. The files looks like the following in a recipe-sysroot:
```
...recipe-sysroot/usr/include/nvidia-kernel-oot/
drivers-private  dt-bindings  linux  media  Module.symvers  soc  tegra_virt_storage_spec.h  trace  uapi  video
```
* The NVIDIA Kernel OOT development Debian package looks like the following:
```
dpkg-deb  -c …
```
> nvidia-kernel-oot: install headers to sysroot-only

- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot-dtb_36.4.0.bb
Currently the device tree file check in `nvidia-kernel-oot-dtb` will always return true because it checks if the filepath is non-empty instead of checking if the file exists at that path.
Fixed by replacing `-z` with `! -f` so it will check if the file actually exists. This will ensure the build session correctly exits if the desired device tree file cannot be found.
Tested by building for the off-the-shelf `jetson-agx-orin-devkit` successfully, then changing `KERNEL_DEVICETREE` to some random string that doesn't exist in the kernel source, and the build would exit instead of continuing.
> Fix device tree file check in nvidia-kernel-oot-dtb

- recipes-support/sbsigntool/sbsigntool/0001-configure-Fixup-build-dependencies-for-cross-compili.patch
* drop the one which says 'Inappropriate [Backport]' as it's either Backport or Inappropriate, but cannot be both
> sbsigntool: Fix Upstream-Status format

- recipes-bsp/uefi/tegra-uefi-capsules_36.4.0.bb
* HOSTTOOLS is now using lz4 instead of lz4c since: https://git.openembedded.org/openembedded-core/commit/?id=fe167e082cbde1c6d186ecdda531abef610ac2ac and tegra-uefi-capsules do_compile is failing with: tegra-uefi-capsules/35.6.0/recipe-sysroot-native/usr/lib/python3.13/subprocess.py", line 1966, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'lz4c' tegra-uefi-capsules/35.6.0/temp/run.do_compile.2229307:369 exit 1 from './doflash.sh'
* I've seen this only with scarthgap-l4t-r35.x branch modified to build for walnascar (master), but it looks like the same is needed in master branch (which has surprisingly to me older version 36.4.0 while scarthgap-l4t-r35.x has 36.6.0, but I don't really use any nvidia …
> tegra-uefi-capsules: add dependency on lz4-native

- recipes-kernel/linux/linux-tegra_5.10.bb
- This matches the behavior in classes/image_types_cboot.bbclass whereby the signed kernel image is copied over the top of the original unsigned kernel image.
> linux-tegra_5.10.bb: fix sign_bootimg

- classes-recipe/image_types_tegra.bbclass
- conf/machine/include/tegra-common.inc
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra-flash-helper.sh
- recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.init.in
- recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.service.in
- recipes-bsp/tools/setup-nv-boot-control/uefi_common.func.in
- recipes-bsp/tools/setup-nv-boot-control_1.0.bb
- recipes-bsp/uefi/edk2-firmware-tegra-36.4.0.inc
- recipes-bsp/uefi/edk2-firmware-tegra_36.4.0.bb
Adds support for the [minimal UEFI](https://docs.nvidia.com/jetson/archives/r36.4/DeveloperGuide/SD/Bootloader/UEFI.html#building-the-miniuefi) configuration.
Also updates the flash helper script to do 'sparse' updates of the SPI flash by default, which is handy for testing UEFI builds.
> Add Minimal UEFI support

- recipes-bsp/tegra-binaries/nvidia-l4t-optee_36.4.0.bb
File in `meta-tegra/recipes-bsp/tegra-binaries/nvidia-l4t-optee_36.4.0.bb` contains wrong references to new version of `libteec`
Error:
```
| install: cannot stat 'build/tmp-glibc/work/armv8a_tegra-oe-linux/nvidia-l4t-optee/36.4.0-20240912212859/nvidia-l4t-optee-36.4.0-20240912212859/usr/lib/libteec.so.1.0.0': No such file or directory
```
Here is the new content of `nvidia-l4t-optee` for `36.4.0`
```
libckteec.so -> libckteec.so.0
libckteec.so.0 -> libckteec.so.0.1
libckteec.so.0.1 -> libckteec.so.0.1.0
libckteec.so.0.1.0
libteeacl.so -> libteeacl.so.0
libteeacl.so.0 -> libteeacl.so.0.1
libteeacl.so.0.1 -> libteeacl.so.0.1.0
libteeacl.so.0.1.0
libteec.so -> libteec.so.2
libteec.so.2 -> libteec.so.2.0.0
libteec.so.2.0 -> libteec.so.2.0.0
libteec.so.2.0.0
```
@ichergui created a new PR for …
> nvidia-l4t-optee: update libteec version

- recipes-bsp/tegra-binaries/gstreamer1.0-plugins-tegra-binaryonly_36.4.0.bb
- recipes-bsp/tegra-binaries/tegra-debian-libraries-common.inc
- recipes-bsp/tegra-binaries/tegra-libraries-dla-compiler_36.4.0.bb
- recipes-bsp/tegra-binaries/tegra-libraries-nvdsseimeta_36.4.0.bb
With the R36 series, the nvidia-l4t-gstreamer package now comes off the 'common' feed instead of the per-SoC feed, which affects multiple recipes.
Add a new variable, L4T_DEB_IS_COMMON, to the include file we use for the BSP recipes, to let them specify that the main package should come from the common feed. Update the recipes for the binary-only gstreamer plugins, nvdsseimeta, and the DLA compiler to use this new mechanism.
Supersedes #1781
> tegra-binaries: refactor per-SoC vs. common deb package handling

- recipes-bsp/uefi/edk2-firmware-tegra-36.4.0.inc
- recipes-bsp/uefi/files/0004-MdePkg-Check-if-compiler-has-__has_builtin-before-tr.patch
when building on Fedora 40, and probably other newer-vintage distros.
> edk2-firmware-tegra: add backported patch for cpp issue

- recipes-kernel/linux/linux-yocto-6.10/0001-NVIDIA-SAUCE-soc-tegra-pmc-Add-sysfs-nodes-to-select.patch
- recipes-kernel/linux/linux-yocto_6.10.bbappend
Solves the issue with `nvbootctrl`. 
```
Current version: 36.4.0
Capsule update status: 1
Current bootloader slot: B
Active bootloader slot: B
num_slots: 2
Error: memory map failed
Info: variable BootChainFwStatus is not found.
Error: memory map failed
Error clear SR value node_name[0]
```
After adding the Nvidia SAUCE:
```
Current version: 36.4.0
Capsule update status: 0
Current bootloader slot: A
Active bootloader slot: A
num_slots: 2
slot: 0,             status: normal
slot: 1,             status: normal
```
Tested with Mender updates
> linux-yocto: add patch to fix compatibility with nvbootctrl

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra-flash-helper.sh
When flashing a board fused with PKC hash but no SBK, we should not supply a SBK key as that would encrypt the flash contents which would then not be able to be read by the board when booting, as the board won't know the SBK key.
This also ideally should be backported to at least the scarthgap and styhead branches.
Fixes: https://github.com/OE4T/meta-tegra/issues/1788
> tegra-flash-helper: Allow PKC-only secure boot flashing

- recipes-devtools/cuda/cuda-compatibility-workarounds/math-vector.h
sinpi/cospi/sinpif/cospif are now defined in glibc as part of C23 extentions but they conflict with CUDA declrations, therefore use the glibc definitions when its provided by glibc
Fixes https://github.com/OE4T/meta-tegra/issues/1784
> cuda-compatibility-workarounds: Fix build with upcoming glibc 2.41

- recipes-devtools/cuda/cuda-cupti_12.6.68-1.bb
nativesdk-cuda-cupti had wrong DEVSUM
This branch should also be merged to master
> Fix DEVSUM x86-64 for cuda-cupti

- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-common.inc
- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-cross-canadian.inc
- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-cross.inc
- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-target.inc
From OE-Core commits 350ff7d and 9221e4a
It's already applied in meta-tegra/scarthgap:
272eccd2 gcc-for-nvcc: backport buildpaths fixes from OE-Core gcc recipes
but wasn't in scarthgap-l4t-r35.x yet
> gcc-for-nvcc: backport buildpaths fixes from OE-Core gcc recipes

- recipes-graphics/drm/libdrm_%.bbappend
- recipes-kernel/nvidia-drm-loadconf/nvidia-drm-loadconf/nvidia-drm-modprobe.conf
- recipes-kernel/nvidia-drm-loadconf/nvidia-drm-loadconf/nvidia-drm-modprobe.conf.in
- recipes-kernel/nvidia-drm-loadconf/nvidia-drm-loadconf_1.0.bb
The nvidia-drm kernel module and associated load config are needed by libdrm but were only getting picked up by weston-init.
There are valid configurations (headless, egl-only) that need libdrm but do not pull in weston, so the runtime recommendation is moved to the libdrm bbappend.
> libdrm: move dependency on nvidia-drm out of weston-init

- recipes-bsp/tegra-sources/tegra-sources-36.4.0.inc
It seems the public_sources.tbz2 tarball hash has changed without content change, which causes builds to fail due to checksum mismatch.
Resolves https://github.com/OE4T/meta-tegra/issues/1798
> tegra-sources: update public_sources.tbz2 hash

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra-flash-helper.sh
With L4T R36.4, the odmsign.func script now supports signing the RCM boot blob used for the initrd-based flashing process. While the initrd-flash script was updated to handle this, more changes are needed to handle signing all binaries during the build.
* Update the flash helper script to run signing on the RCM boot blob when needed.
* Update the initrd-flash script to drop the extra helper invocation for signing the RCM boot blob, since that is now covered with the normal signing step for the internal flash. And when pre-signed, initrd-flash just looks for the RCM boot blob in the subdirectory now created during build-time signing.
Fixes #1698
> tegra-helper-scripts: fix RCM boot blob signing

- recipes-bsp/uefi/edk2-firmware-tegra-35.6.0.inc
As discussed in [1], [2], and [3], AGX Xavier targets are no longer able to write any persistent variables from edk boot, and are no longer to perform capsule updates after 355 reboots.
Pull in the patch in [4] which is confirmed to resolve this issue as tested on AGX Xavier with 500 reboots using the script at [5] plus a capsule update test.
1: https://forums.developer.nvidia.com/t/possible-uefi-memory-leak-and-partition-full/308540/43
2: https://forums.developer.nvidia.com/t/redundant-a-b-rootfs-not-switching-with-set-active-boot-slot-but-working-with-set-sr-br/306475/27
3: https://github.com/NVIDIA/edk2-nvidia/issues/114
4: https://github.com/NVIDIA/edk2-nvidia/commit/c101ba515b2737fb78d8929c2852f5c8f9607330
5: https://github.com/Trellis-Logic/linux-test-scripts/blob/main/tegra_uefi_reb …
> edk2-firmware-tegra: fix agx xavier peristent vars

- recipes-security/optee/optee-l4t.inc
Make sure we have proper path to MM even when building from devtool workspace.
> optee-os: make build work in devtool

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra-flash-helper.sh
- recipes-security/optee/optee-l4t.inc
* Fixed a typo that would omit some DTB overlays for some cases
* Reworked the use of the RCM boot blob signing in the `odmsign.func` functions so the signed files for RCM booting don't end up replacing the main signed files
* Signing step in initrd-flash now skips signing partitions on external storage devices
* Since booting using pre-signed boot firmware prevents us from reading the CVM EEPROM to get the serial number, added a mechanism for locating the right storage device based on the USB instance being in the device path
Tested with a secured and an unsecured device.
Fixes #1813 
Fixes #1803
Also includes a fix for the buildpath errors that were introduced with #1808
> More fixes for getting initrd flashing to work with pre-signed binaries

- recipes-bsp/tegra-binaries/tegra-configs/l4t.csv
Fixes `(Argus) Error InvalidState: Failed to load EGL library`  issue described here:
https://github.com/OE4T/meta-tegra/issues/1518
by mounting /usr/lib/aarch64-linux-gnu/tegra-egl/libEGL_nvidia.so.0 into the container
> l4t.csv: add tegra-egl/libEGL_nvidia.so.0

- recipes-kernel/linux/linux-yocto_6.6.bbappend
Patch was ported and committed but not the changes to the recipe.
Fixes 13d3075d7fec0fef920fd182e634a1ec8cf239c2
Refs #1833
> linux-yocto: add ported pmc sysfs nodes patch to bbappend

- recipes-bsp/uefi/tegra-uefi-capsules_36.4.3.bb
With https://github.com/OE4T/meta-tegra/commit/9b6a113255d552cd2c9db32cef93676e93b5e2c3 the image_types_tegra class was modifed to add the minimal uefi image, uefi_jetson_minimal, to the tegraflash package and added edk2-firmware-tegra-minimal:do_deploy to the do_image_tegraflash_tar[depends]
Since tegra-uefi-capsules also references tegraflash_populate_package it also needs the same dependency to avoid this build error:
```
| DEBUG: Executing shell function do_compile
| cp: cannot stat '/home/dan/trellis/oe4t/tegra-demo-distro/build-r36.4.3/tmp/deploy/images/jetson-orin-nano-devkit-nvme/uefi_jetson_minimal.bin': No such file or directory
| WARNING: exit code 1 from a shell command.
```
I considered a more complicated fix here to assign a new variable
```
TEGRAFLASH_POPULATE_DEPENDS = …
```
> tegra-uefi-capsules: add minimal UEFI dependency

- recipes-devtools/cuda/cuda-cudart_12.6.68-1.bb
- recipes-devtools/cuda/cuda-nvcc_12.6.68-1.bb
* Fix cuda-cudart-dev RDEPENDS to reference cuda-crt-dev instead of cuda-crt
* Add cuda-nvvm as runtime dependency for nativesdk nvcc so cicc gets installed
Fixes #1839
> SDK fixes for CUDA 12

- conf/machine/p3737-0000-p3701-0004.conf
which missed getting updated for the OOT device trees that were switched to in L4T R36.x.
Fixes #1843
> p3737-0000-p3701-0004: fix KERNEL_DEVICETREE setting

- recipes-kernel/linux/linux-tegra_5.10.bb
I'm not sure why but I've hit this on two different projects this week, one using `kirkstone` branch and one using `dunfell`.
I wrote a script to attempt to reproduce on tegra-demo-distro and ran about 100 clean/rebuild steps overnight but could not reproduce.  I think it's got something to do with changes in proprietary layers on each of these projects which are causing subtle timing differences.  On one of the projects I can make this happen every time I run `bitbake -c cleansstate linux-tegra && bitbake linux-tegra`
Let me know if there's a better way to fix this, or if you'd prefer adding a dependency on `make-mod-scripts`.  It seems like we can't allow `do_compile_kernelmodules` and `do_compile_devicetree_overlays` to run in parallel though since they are both going to attempt to run …
> linux-tegra: fix devicetree scripts dependency

- recipes-bsp/tools/tegra-eeprom-tool_2.0.2.bb
tegra-eeprom-tool is broken in scarthgap since eeprom is defined as read-only on L4T R36.4.0/JetPack 6.1.
> tegra-eeprom-tool: update v2.0.1 -> v2.0.2

- recipes-bsp/uefi/tegra-uefi-capsules_36.4.0.bb
- 'mv generate_bup_payload.sh doflash.sh' should be conditional on TEGRA_SIGNING_EXCLUDE_TOOLS.  Those who use external signing servers will set this to "1" which skips the generation of generate_bup_payload.sh.  See invocations of tegraflash_generate_bupgen_script in image_types_tegra.bbclass.
> tegra-uefi-capsules: fix signing with external server

- recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.sh.in
- recipes-bsp/tools/setup-nv-boot-control_1.0.bb
Found when testing https://github.com/OE4T/tegra-demo-distro/pull/320 with the test procedure there on AGX Xavier devices.  I believe it's necessary for this commit or something like it on any Jetpack 5 AGX Xavier based targets to be applied and implemented before slot switching through nvbootctrl to work properly.
I considered defining `TNSPEC_COMPAT_MACHINE` in the include file for agx-xavier but not sure we want to make that change, especially on a stable branch, at this point, because I'm not sure what side effect changing the compatible spec will have for already deployed devices.
Also based on the discussion at https://forums.developer.nvidia.com/t/nvbootctrl-hardcoded-to-only-handle-agx-xavier/270411/4 I suspect this probably only applies to AGX Xavier.
I think I may just make a …
> setup-nv-boot-control: add COMPAT_TARGET

- external/virtualization-layer/recipes-containers/libnvidia-container/libnvidia-container/0002-fix-building-with-go-1-24.patch
- external/virtualization-layer/recipes-containers/libnvidia-container/libnvidia-container_1.16.2.bb
With backported patch at https://github.com/NVIDIA/libnvidia-container/pull/297 supporting go 1.24+.
Resolves
```
| # nvcgo
| ./main.go:35:10: cannot define new methods on non-local type CDeviceRule
| make[2]: *** [Makefile:40: libnvidia-container-go.so] Error 1
```
> libnvidia-container: fix go build on 36.4.3

- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot_36.4.0.bb
- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot_git.bb
When device-tree builds moved to nvidia-kernel-oot, the dtb files built from the platform dts files were getting stashed into the sysroot area for future use during image build, but the dts files themselves were *not* saved anywhere. This broke external device-tree recipes that wanted to include the platform dts and add modifications.
Add export of dts files into nvidia-kernel-oot sysroot area, under usr/src/device-tree subdir.
> nvidia-kernel-oot: support external device-tree recipes

- recipes-graphics/mesa/tegra-udrm-gbm_1.1.1.bb
This version emits a different internal name so it passes a check added to egl-gbm at version 1.1.1. This does not alter functionality in any way.
> tegra-udrm-gbm: update for compatibility with egl-gbm 1.1.1+

- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot.inc
The module media and other modules are reusable for other modules, the package
should expose symbols to other packages.
The `module.bbclass` expects `kernel-module-` prefix package name and matching
include directory to trigger the dependency mechanism.
```
python __anonymous () {
depends = d.getVar('DEPENDS')
extra_symbols = []
for dep in depends.split():
if dep.startswith("kernel-module-"):
extra_symbols.append("${STAGING_INCDIR}/" + dep + "/Module.symvers")
d.setVar('KBUILD_EXTRA_SYMBOLS', " ".join(extra_symbols))
}
```
Add:
1. `kernel-module-nvidia-kernel-oot` `PROVIDES` alias.
2. Symlink of `/usr/include/kernel-module-nvidia-kernel-oot -> /usr/include/nvidia-kernel-oot`
A module that requires these modules can use the standard dependency such as:
```    
DEPENDS += …
```
> nvidia-kernel-oot: support module symbol reuse

- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot/0001-nvidia-kernel-oot-handle-of_property_for_each_u32-ap.patch
- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot_36.4.3.bb
of_property_for_each_u32() only takes three arguments in newer kernels.
> nvidia-kernel-oot: fix linux-yocto build

- conf/machine/include/agx-orin.inc
- conf/machine/include/orin-nano.inc
- conf/machine/include/orin-nx.inc
- conf/machine/jetson-agx-orin-devkit-industrial.conf
EMMC_SIZE has been superseded by ROOTFSPART_SIZE for defining the size of the root filesystem partitions directly.
This commit removes leftover assignments in the machine configurations.
> remove leftover mentions of EMMC_SIZE

- recipes-bsp/tegra-binaries/tegra-helper-scripts/make-sdcard.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/nvflashxmlparse.py
If the `filesystem_type` field in the NVIDIA XML layout is set to a value other than `'basic'`, the script will prepare the partition using the specified type.
According to the [official documentation](https://docs.nvidia.com/jetson/archives/r36.4.4/DeveloperGuide/AR/BootArchitecture/PartitionConfiguration.html#partition-child-elements), only 'basic' is expected, and support for ext2 is deprecated. However, with this modification, other filesystem types remain supported.
This change can be particularly useful for users who need to define custom partition types beyond what the default layout allows.
> make-sdcard: Improve script to create filesystems if needed

- recipes-bsp/tegra-binaries/files/0010-Rework-logging-in-l4t_sign_image.sh.patch
The patch for l4t_sign_image.sh seems to have removed "echo" from the logging line. I've had a patch for this patch file in my BSP layer for a while and I decided I would get it submitted.
> l4t_sign_image.sh patch: fix missing 'echo' in logging line

- classes-recipe/tegra-uefi-signing.bbclass
- recipes-bsp/tegra-binaries/tegra-uefi-prebuilt_36.4.4.bb
- recipes-bsp/uefi/edk2-firmware-tegra_36.4.4.bb
- recipes-bsp/uefi/l4t-launcher-extlinux.bb
- recipes-kernel/linux/tegra-kernel.inc
- recipes-kernel/nvidia-kernel-oot/nvidia-kernel-oot.inc
This makes it possible for the build to track key/cert files defined by TEGRA_UEFI_DB_KEY/TEGRA_UEFI_DB_CERT.
Changes made to those files are kept up to date in the build.
For this to work, instead of specifying the full path for the key/cert files in TEGRA_UEFI_DB_KEY/TEGRA_UEFI_DB_CERT user must specify the file names.
The path for where key/cert are located must be provided in the variable TEGRA_UEFI_DB_PATH
> uefi signing: tracks UEFI DB files with file-checksums 

- recipes-bsp/uefi/edk2-firmware-tegra-36.4.4.inc
- recipes-bsp/uefi/files/0007-BaseTools-Pccts-set-C-standard.patch
needed for build host toolchains that use gcc 15.
Fixes #1983
> edk2-firmware-tegra: back-port another GCC 15 compatibility patch

- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-target.inc
Since the commit gcc-for-nvcc: clean up after upgrade to 13.2 sha: 47b7d680d667a77b9fc1e231f9b6e53d2bc9941f
the command populate_sdk were not working.
I have removed the line causing this (do not create not used folder into the installation).
Should be merged into scarthgap, master, walnascar as well.
(for Walnascar, I saw that both commit 117b855d25783a0b10a4ca4404af1b5718af0279 & 47b7d680d667a77b9fc1e231f9b6e53d2bc9941f were not merged into this branch but only master).
> gcc-for-nvcc: fix populate sdk

- recipes-devtools/gie/tensorrt-core_10.3.0.30-1.bb
TensorRT dropped the libnvparsers libraries in version 10, so drop the creation of symlinks to the now-nonexistent libraries.
See #1972
> tensorrt-core: remove broken symlinks

- classes-recipe/image_types_tegra.bbclass
This change addresses an issue where the `image_types_tegra.bbclass` was incorrectly depending on the `do_populate_sysroot` task of `tegra-uefi-keys-dtb` package while looking for files from that recipe in the `DEPLOYDIR` directory.  Without an explicit dependency on do_deploy, those files are not correctly 'staged' and builds will fail IF `tegra-uefi-keys-dtb:do_deploy` has not yet run.  By adding the `do_deploy` task as a dependency, it ensures the files are correctly staged for the image recipe to succeed.
> fix: update image_types_tegra task dependency for uefi keys dtb
