OE4T/meta-tegra

- recipes-bsp/tegra-binaries/tegra-flashtools-native_24.2.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries_24.2.1.bb
- recipes-devtools/cuda/cuda-binaries-native_6.5-53.bb
- recipes-devtools/cuda/cuda-binaries-native_8.0.34-1.bb
- recipes-devtools/cuda/cuda-binaries_6.5-53.bb
- recipes-devtools/cuda/cuda-binaries_8.0.34-1.bb
I don't use tegra for anything, these are just fixes for build issues detected by my world builds when includes meta-tegra layer while building for other MACHINEs.
> Various small fixes for morty

- recipes-bsp/tegra-binaries/tegra-libraries_28.1.0.bb
- recipes-bsp/tegra-binaries/tegra186-flashtools-native_28.1.0.bb
- recipes-bsp/tegra-binaries/tegra210-flashtools-native_28.1.0.bb
- recipes-devtools/cuda/cuda-binaries-native_6.5-53.bb
- recipes-devtools/cuda/cuda-binaries-native_8.0.84-1.bb
- recipes-devtools/cuda/cuda-binaries_6.5-53.bb
- recipes-devtools/cuda/cuda-binaries_8.0.84-1.bb
- recipes-devtools/cuda/cuda-command-line-tools_8.0.84-1.bb
- recipes-kernel/linux/linux-tegra_4.4.bb
I don't use tegra for anything, these are just fixes for build issues detected by my world builds when includes meta-tegra layer while building for other MACHINEs.
> Various small fixes for rocko

- recipes-bsp/tegra-binaries/tegra-flashtools-native_24.2.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries_24.2.1.bb
- recipes-bsp/tegra-binaries/tegra-libraries_27.1.0.bb
- recipes-devtools/cuda/cuda-binaries-native_6.5-53.bb
- recipes-devtools/cuda/cuda-binaries-native_8.0.34-1.bb
- recipes-devtools/cuda/cuda-binaries_6.5-53.bb
- recipes-devtools/cuda/cuda-binaries_8.0.34-1.bb
- recipes-devtools/cuda/cuda-command-line-tools_8.0.34-1.bb
- recipes-devtools/cuda/cuda-toolkit_8.0.34-1.bb
I don't use tegra for anything, these are just fixes for build issues detected by my world builds when includes meta-tegra layer while building for other MACHINEs.
> Various small fixes for pyro

- recipes-bsp/alsa-state/alsa-state.bbappend
Need to set ship package to fix error `alsa-state: 1 installed and not shipped files. [installed-vs-shipped]`
> alsa shipp into /etc/

- conf/layer.conf
Set LAYERSERIES_COMPAT for this branch of meta-tegra to rocko.
> conf/layer.conf: Set LAYERSERIES_COMPAT

- README
Add a link to the wiki page describing use of Linaro for GCC7
See discussion in #185
> Update README for Linaro GCC 7 support

- README
Add a bracket at the end of the sentence for Jetson-TX1.
> README: Minor fix

- recipes-graphics/libglvnd/libglvnd_1.2.0.bb
- recipes-graphics/mesa/mesa_%.bbappend
Modified version to address the issue mentioned in PR #247
> Update runtime dependencies for libglvnd/mesa

- contrib/recipes-devtools/gcc/libgcc-initial_7.3.bb
Code cleanup to remove dummy source which is not needed.
> libgcc-initial: Code cleanup

- recipes-core/initrdscripts/tegra-minimal-init/init-boot.sh
Optionally run any custom initialization just before switching the rootfs
> Add platform-pre-switchroot

- contrib/recipes-test/tegra-tests/gpu-burn_git.bb
This pull requset resolves the following issue in test-distro: madisongh/test-distro#4
Signed-off-by: Shlomi Vaknin <shlomi.39sd@gmail.com>
> Move gpu-burn from test distro to meta-tegra/contrib

- classes/cuda.bbclass
Note that a patch is required for meson 0.55 to
fix an issue with identifying CUDA compiler when
cross-building (see #409).
> cuda.bbclass: add support for meson builds

- recipes-kernel/linux/linux-tegra_4.9.bb
to pick up a fix for the SPI driver.
Fixes #454
> linux-tegra: bump SRCREV

- LICENSE
> LICENSE: update copyright

- recipes-bsp/u-boot/u-boot-tegra_2020.10.bb
to pick up all updates from v2020.10
> u-boot-tegra: update source revision

- conf/machine/include/xavier-nx.inc
> Fix Xavier NX machine overrides

- recipes-bsp/u-boot/u-boot-tegra_2020.04.bb
to pick up some additional patch.
> u-boot-tegra: bump SRCREV

- recipes-devtools/vpi/libnvvpi1/0001-vpi-config-allow-to-compute-the-installation-prefix.patch
- recipes-devtools/vpi/libnvvpi1_1.0.15.bb
Add recipe for installing the Nvidia VPI library.
> libnvvpi1: add recipe

- classes/image_types_tegra.bbclass
- recipes-bsp/tegra-binaries/tegra-helper-scripts/nvflashxmlparse.py
* Updates the `nvflashxmlparse` script with a function to split a flash layout into two, with the rootfs, kernel, kernel-dtb, and UDA partitions put on a separate SDcard device and the rest of the partitions retained on the on-board eMMC
* Updates the tegraflash bundle to optionally include a `dosdcard.sh` script.
* Only supports the Jetson AGX Xavier dev kit (`MACHINE = "jetson-agx-xavier-devkit"`)
* Does **not** support A/B redundancy.  Boots from the B slot always fail during MB1.
To use, set the following variables in your build configuration:
```
TEGRA_ROOTFS_AND_KERNEL_ON_SDCARD = "1"
ROOTFSPART_SIZE = "15032385536"
```
The rootfs partition size above is for a 16GB SDcard. If you use a different size card, adjust accordingly (but be warned that the SDcard flash XML file may also …
> rootfs and kernel on SDcard for AGX Xavier

- recipes-devtools/nsight-systems/nsight-systems-cli_2020.5.3.17.bb
Add recipe for installing libraries and tools of Nvidia Nsight Systems CLI.
> nsight-systems-cli: add recipe

- classes/image_types_tegra.bbclass
- conf/machine/include/tegra210.inc
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra186-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
> In build signing fixes - 32.4.3

- classes/image_types_tegra.bbclass
- conf/machine/include/tegra210.inc
- recipes-bsp/tegra-binaries/files/0009-Remove-xxd-dependency-from-l4t_sign_image.sh.patch
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra186-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
- recipes-bsp/tegra-binaries/tegra186-flashtools-native_32.5.1.bb
> In build signing 32.5

- external/meta-python/recipes-devtools/python3-tensorrt/python3-tensorrt/0001-Do-not-overwrite-CMAKE_CXX_FLAGS.patch
- external/meta-python/recipes-devtools/python3-tensorrt/python3-tensorrt/0002-pyOnnx-fixups-for-TensorRT-7.1-API.patch
- external/meta-python/recipes-devtools/python3-tensorrt/python3-tensorrt_7.1.3-1.bb
> python3-tensorrt: add recipe

- recipes-kernel/linux/linux-tegra-upstream_5.12.bb
> linux-tegra-upstream: add KBRANCH and SRCPV.

- contrib/recipes-devtools/gcc-8/gcc-8.3.inc
- contrib/recipes-devtools/gcc-8/gcc-8.3/0044-libsanitizer-remove-cyclades.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.9.0/0005-Update-makefile-for-statically-linking-external-libt.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.9.0.bb
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libtirpc126_1.2.6.bb
* Partially address #760 (just the segfault issue)
* Fixes #761
> Fixes for master

- conf/machine/include/tegra-common.inc
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.10.0/0001-Makefile-Fix-RCP-flags-and-change-path-definitions-s.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.10.0/0002-mk-common.mk-set-JETSON-variable-if-not-set-before.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.10.0/0003-Fix-mapping-of-library-paths-for-jetson-mounts.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.10.0/0004-Fix-build.h-generation-for-cross-builds.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.10.0.bb
> libnvidia-container-tools: upgrade to 0.10.0 to aligned with L4T R32.6.1

- recipes-core/images/tegra-minimal-initramfs.bb
> tegra-minimal-initramfs: fix typo

- recipes-devtools/cuda/cuda-nvrtc_10.2.300-1.bb
- recipes-multimedia/argus/argus-samples/0001-argus-apps-camera-replace-xxd-invocation-with-shell-.patch
- recipes-multimedia/argus/argus-samples_32.6.1.bb
- recipes-multimedia/argus/tegra-mmapi-32.6.1.inc
- recipes-multimedia/argus/tegra-mmapi-samples/0001-include-fix-jpeglib-header-inclusion.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0002-tools-update-GetPixel.py-to-Python-3.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0003-samples-classes-fix-a-data-race-in-shutting-down-deq.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0004-samples-support-tegra_udrm-in-NvDrmRenderer.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0005-Remove-DO-NOT-USE-declarations-from-v4l2_nv_extensio.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0006-samples-Rework-makefiles-and-rules.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0007-trt_inference-use-smart-pointers-during-model-conver.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0008-frontend-add-option-to-set-timeout.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0009-camera_v4l2_cuda-add-option-for-setting-max-frame-co.patch
- recipes-multimedia/argus/tegra-mmapi-samples_32.6.1.bb
- recipes-multimedia/argus/tegra-mmapi_32.6.1.bb
The `tegra-mmapi-samples` and `argus-samples` recipes have been living in the demo distro for a while now.
A bit of cleanup, particularly to `tegra-mmapi-samples`, is all that's needed to move them here.
> Pull in mmapi samples

- recipes-devtools/cuda/cuda-nvrtc_10.2.300-1.bb
- recipes-multimedia/argus/argus-samples/0001-argus-apps-camera-replace-xxd-invocation-with-shell-.patch
- recipes-multimedia/argus/argus-samples_32.6.1.bb
- recipes-multimedia/argus/tegra-mmapi-32.6.1.inc
- recipes-multimedia/argus/tegra-mmapi-samples/0001-include-fix-jpeglib-header-inclusion.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0002-tools-update-GetPixel.py-to-Python-3.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0003-samples-classes-fix-a-data-race-in-shutting-down-deq.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0004-samples-support-tegra_udrm-in-NvDrmRenderer.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0005-Remove-DO-NOT-USE-declarations-from-v4l2_nv_extensio.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0006-samples-Rework-makefiles-and-rules.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0007-trt_inference-use-smart-pointers-during-model-conver.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0008-frontend-add-option-to-set-timeout.patch
- recipes-multimedia/argus/tegra-mmapi-samples/0009-camera_v4l2_cuda-add-option-for-setting-max-frame-co.patch
- recipes-multimedia/argus/tegra-mmapi-samples_32.6.1.bb
- recipes-multimedia/argus/tegra-mmapi_32.6.1.bb
> Pull in mmapi samples - dunfell

- recipes-bsp/u-boot/u-boot-bup-payload.bb
> u-boot-bup-payload: add dtc-native into dependency list

- conf/layer.conf
- conf/machine/include/tegra-common.inc
- external/meta-python/recipes-devtools/python3-tensorrt/python3-tensorrt_8.0.1.bb
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins/0001-CMakeLists.txt-fix-cross-compilation-issues.patch
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins_8.0.1-1.bb
- recipes-devtools/deepstream/deepstream-5.1_5.1.0-1.bb
- recipes-devtools/gie/tensorrt-core_8.0.1-1.bb
- recipes-devtools/gie/tensorrt-plugins-prebuilt_8.0.1-1.bb
- recipes-devtools/gie/tensorrt-samples/0001-Makefile-fix-cross-compilation-issues.patch
- recipes-devtools/gie/tensorrt-samples_8.0.1-1.bb
- recipes-multimedia/argus/tegra-mmapi-samples_32.6.1.bb
* This PR is a backport from `master` branch to `dunfell`
> Dunfell: Build TensorRT Plugins from source

- conf/layer.conf
- conf/machine/include/tegra-common.inc
- external/meta-python/recipes-devtools/python3-tensorrt/python3-tensorrt_7.1.3-1.bb
- external/meta-python/recipes-devtools/tensorrt-samples/tensorrt-samples/0001-Makefile-fix-cross-compilation-issues.patch
- external/meta-python/recipes-devtools/tensorrt-samples/tensorrt-samples_7.1.3-1.bb
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins/0001-CMakeLists.txt-fix-cross-compilation-issues.patch
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins/0002-parsers-onnx-remove-constexpr.patch
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins_7.1.3-1.bb
- recipes-devtools/deepstream/deepstream-5.1_5.1.0-1.bb
- recipes-devtools/gie/tensorrt-core_7.1.3-1.bb
- recipes-devtools/gie/tensorrt-plugins-prebuilt_7.1.3-1.bb
- recipes-multimedia/argus/tegra-mmapi-samples_32.5.1.bb
* This PR is a backport from `dunfell` branch to `dunfell-l4t-r32.5.0`
> dunfell-l4t-r32.5.0: Build TensorRT Plugins from source

- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins/0001-CMakeLists.txt-fix-cross-compilation-issues.patch
- external/openembedded-layer/recipes-devtools/gie/tensorrt-plugins/0002-Tensorrt-fix-build-issues-when-using-protobuf-versio.patch
> tensorrt-plugins: fix warning fuzz detected when applying patches.

- recipes-devtools/deepstream/deepstream-6.0_6.0.0-1.bb
> deepstream: update to 6.0

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra186-flash-helper.sh
- recipes-multimedia/nvbufsurface/nvbufsurface-headers_6.0.0-1.bb
> Update board SKU handling in tegra186-flash-helper

- conf/machine/include/tegra-common.inc
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.10.0/0001-Makefile-Fix-RCP-flags-and-change-path-definitions-s.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.10.0/0002-mk-common.mk-set-JETSON-variable-if-not-set-before.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.10.0/0003-Fix-mapping-of-library-paths-for-jetson-mounts.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools-0.10.0/0004-Fix-build.h-generation-for-cross-builds.patch
- external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.10.0.bb
- recipes-bsp/tegra-binaries/tegra-libraries_32.5.2.bb
Fix issue #770 in the dunfell-l4t-r32.5.0 branch.
> dunfell-l4t-r32.5.0: pull in container runtime fixes from dunfell

- recipes-devtools/cudnn/cudnn-samples_8.3.2.49-1.bb
- recipes-devtools/cudnn/cudnn_8.3.2.49-1.bb
> cudnn: split recipe to cudnn, cudnn-samples

- recipes-security/optee/optee-client-prebuilt_34.1.0.bb
- recipes-security/optee/optee-prebuilt.inc
- recipes-security/optee/optee-test-prebuilt_34.1.0.bb
this enable OPTEE Client and test suite for TEE
> optee: add optee-client-prebuilt, optee-test-prebuilt recipe

- conf/machine/include/tegra234.inc
- recipes-bsp/tegra-binaries/tegra-configs_34.1.0.bb
- recipes-kernel/nvidia-display-driver/nvidia-display-driver/0001-arm64-set-mno-outline-atomics-and-fno-stack-protecto.patch
- recipes-kernel/nvidia-display-driver/nvidia-display-driver_34.1.0.bb
This add display driver support for tegra234
> nvidia-display-driver: add recipe

- recipes-devtools/gie/tensorrt-core_8.4.1-1.bb
Fixes issue with demo-image-full build.
See discussion at [1]
1: https://gitter.im/OE4T/jetpack-5-test?at=62fee02f9994996293de8fb1
Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>
> tensorrt-core: Update license check

- recipes-multimedia/argus/tegra-mmapi-samples/0002-tools-update-GetPixel.py-to-Python-3.patch
All changes but one of [1] were already incorporated in the r35.1
release.  See thread at [2]
1: https://github.com/OE4T/meta-tegra/commit/0050144b2973e544237e53ecee65dee85e5cc8f9#diff-9d779250de06e384fc1e77959ef1a11165c69a34de15346d3c592d78f44f2ac9
2: https://gitter.im/OE4T/jetpack-5-test?at=62fee02f9994996293de8fb1
Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>
> tegra-mmapi-samples: Update GetPixel.py patch

- conf/layer.conf
> layer.conf: drop obsolete siggen exclusions

- classes/image_types_tegra.bbclass
- recipes-bsp/tegra-binaries/tegra-redundant-boot-rollback_35.1.0.bb
Refs d4f946d4c82556c9ca4e421f051adb337346fcd9
> TNSPEC_MACHINE: fix a couple missing subsitutions

- recipes-multimedia/gstreamer/gstreamer1.0-plugins-nvjpeg_1.14.0-r35.1.0.bb
> gstreamer1.0-plugins-nvjpeg: fix LIC_FILES_CHKSUM

- external/openembedded-layer/recipes-extended/haveged/haveged/haveged.service
- external/openembedded-layer/recipes-extended/haveged/haveged_%.bbappend
- recipes-bsp/trusty/hwkey-app.bb
- recipes-bsp/trusty/luks-srv-app.bb
Cherry-pick "haveged: reintroduce systemd service" from master
Add recipe for hwkey-app Client Application to communicate with hwkey-agent Trusted Application
Add recipe for luks-srv-app Client Application to communicate with luks-srv Trusted Application
> Kirkstone trusty apps

- classes/image_types_tegra.bbclass
Kirkstone missing the following commit for virtual/dtb support:
---
image_types_tegra: add support for virtual/dtb provider
This change adds support (adapted from kernel-fitimage handling) for out-of-tree device tree binary generation. It looks for a provider of virtual/dtb, and if this exists, enables the copying of device tree binaries generated by this recipe.
> Backport virtual/dtb fix for kirkstone

- classes/image_types_tegra.bbclass
- conf/machine/include/tegra-common.inc
- conf/machine/include/tegra186.inc
- conf/machine/include/tegra194.inc
- conf/machine/include/tegra210.inc
- recipes-core/images/tegra-initrd-flash-initramfs.bb
Back-porting/adapting #1140 for R32.7.x
> Make initrd-flash support optional

- recipes-bsp/tegra-binaries/tegra-brcm-patchram_35.2.1.bb
> tegra-brcm-patchram: update checksum

- external/openembedded-layer/recipes-support/opencv/opencv_4.6.%.bbappend
> opencv: add missing whitespace

- classes/image_types_tegra.bbclass
> Restore mksparse in common post-sign function

- recipes-bsp/uefi/edk2-firmware-tegra-35.2.1.inc
- recipes-bsp/uefi/files/0001-Fix-eeprom-customer-part-numbers.patch
Patch updated to make it apply at the same level as others in series.
> edk2-firmware-tegra: Update patch relative to work dir

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh
> Remove fuselevel check in t194 flash helper

- recipes-bsp/tegra-binaries/files/0013-Fix-location-of-bsp_version-file-in-l4t_bup_gen.func.patch
- recipes-bsp/tegra-binaries/files/0016-Update-tegraflash_impl_t234.py.patch
- recipes-bsp/tegra-binaries/tegra-flashtools-native_35.2.1.bb
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra234-flash-helper.sh
Script updates to fix build failures for Orin devices when using secure boot with combined SBK+PKC.
> t234 signing fixes

- recipes-devtools/gcc-for-nvcc/gcc-8-common.inc
- recipes-devtools/gcc-for-nvcc/gcc-8-cross-canadian.inc
- recipes-devtools/gcc-for-nvcc/gcc-8-crosssdk.inc
fixes https://github.com/OE4T/meta-tegra/issues/1246
> [backport] crosssdk is droped in oe-core

- conf/machine/include/tegra194.inc
Signed-off-by: Damien LEFEVRE <lefevre.da@gmail.com>
> Added support for Xavier FAB 401

- recipes-multimedia/argus/tegra-mmapi-35.4.1.inc
- recipes-multimedia/argus/tegra-mmapi-samples/0005-samples-Rework-makefiles-and-rules.patch
- recipes-multimedia/argus/tegra-mmapi-samples_35.4.1.bb
- refresh patch
- update License
- add vulkan as dependency
> tegra-mmapi-samples: fix build issues

- recipes-bsp/uefi/tegra-uefi-capsules_35.3.1.bb
deploy class flushes from DEPLOYDIR to DEPLOY_DIR_IMAGE as an sstate task.
> Adds deploy task for capsules

- recipes-bsp/tegra-binaries/tegra-configs/l4t.csv
Work in progress changes.  Building but not yet tested.
See related PR at https://github.com/OE4T/meta-tegra/pull/1310#issuecomment-1666995941 which will probably be needed for testing this.
> nvidia-docker l4t r35.4.1 changes

- recipes-bsp/uefi/edk2-firmware-tegra-35.4.1.inc
- recipes-bsp/uefi/files/0001-Disable-outline-atomics-in-eqos-driver.patch
- recipes-bsp/uefi/files/0001-Use-bfd-linker.patch
- recipes-bsp/uefi/files/0002-Fix-RCM-boot-detection.patch
- recipes-bsp/uefi/files/0003-L4TLauncher-allow-for-empty-missing-APPEND-line-in-e.patch
Split the patches in groups and apply on the corresponding directory.
Fix https://github.com/OE4T/meta-tegra/issues/1046
> edk2-firmware-tegra: refresh patches

- external/openembedded-layer/recipes-extended/haveged/haveged_%.bbappend
- recipes-bsp/tegra-binaries/tegra-nvphs/nvphs.service
- recipes-bsp/tegra-binaries/tegra-nvphs_32.7.4.bb
- recipes-bsp/tegra-binaries/tegra-nvpmodel/nvpmodel.init
- recipes-bsp/tegra-binaries/tegra-nvpmodel/nvpmodel.service
- recipes-bsp/tegra-binaries/tegra-nvpmodel_32.7.4.bb
* Add a bbappend to fix its init script
* Minor fixes for the nvpmodel and nvphs startup files 
Related to #1364
> Haveged, nvpmodel, and nvphs startup fixes for dunfell

- external/openembedded-layer/recipes-extended/haveged/haveged_%.bbappend
- recipes-bsp/tegra-binaries/tegra-nvphs_32.7.4.bb
- recipes-bsp/tegra-binaries/tegra-nvpmodel/nvpmodel.init
- recipes-bsp/tegra-binaries/tegra-nvpmodel_32.7.4.bb
> More initscript updates

- classes/image_types_tegra.bbclass
to take the list of boot control overlays as arguments rather than using the TEGRA_BOOTCONTROL_OVERLAYS variable directly, and update the invocations to use the Python function that adds in the appropriate overlay for UEFI keys when UEFI secure boot is in use.
Fixes #1367
> image_types_tegra.bbclass: update copy_dtb_overlays function

- recipes-devtools/nsight-systems/nsight-systems-cli_2023.2.4.44-33011852v0.bb
This aligns with 5.2.1 from https://repo.download.nvidia.com/jetson/#Jetpack%205.1.2
> Upgrade nsight-systems to 2023.2.4

- external/openembedded-layer/recipes-multimedia/v4l2apps/v4l-utils/0001-Make-plugin-directory-relative-to-ORIGIN.patch
- recipes-bsp/tegra-binaries/tegra-debian-libraries-common.inc
- recipes-graphics/l4t-graphics-demos/l4t-graphics-demos_35.4.1.bb
- recipes-graphics/wayland/weston/0001-libweston-tools-Include-libgen.h-for-basename-signat.patch
- recipes-graphics/wayland/weston_10.0.2.bb
- recipes-security/optee/optee-nvsamples_35.4.1.bb
With these fixes we can get musl based images building as well.
> Add assorted musl fixes

- recipes-bsp/tegra-binaries/tegra-helper-scripts/initrd-flash.sh
Partially address https://github.com/OE4T/meta-tegra/pull/1424
> initrd-flash: set pipefail option

- conf/machine/include/orin-nano.inc
- conf/machine/p3768-0000-p3767-0004.conf
8GB module: board SKU 0003 or 0005
4GB module: board SKU 0004
Fixes #1531
> conf/machine: fix boardsku settings for Orin Nano modules

- recipes-devtools/cuda/cuda-nvvm_12.2.140-1.bb
- update sha256sum
- restructure the DEB package to facilitate compile and install tasks
> cuda-nvvm: update recipe

- recipes-devtools/nsight-systems/nsight-systems_2024.2.2.28-242234212449v0.bb
> nsight-systems: update LIC_FILES_CHKSUM

- recipes-bsp/arm-trusted-firmware/arm-trusted-firmware_2.8-l4t-r36.3.0.bb
- this allows ability to modify these in other layers if needed
> arm-trusted-firmware: set DEBUG and LOG_LEVEL from bitbake

- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-common.inc
- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-cross-canadian.inc
- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-cross.inc
- recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-target.inc
> gcc: backport QA fixes from poky/gcc recipes

- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra-flash-helper.sh
Tests were done on `Jetson Orin AGX` and `Orin AGX Industrial`
```
root@jetson-agx-orin-devkit:~# uname -a 
Linux jetson-agx-orin-devkit 5.15.148-l4t-r36.4-1012.12+g8dc079d5c8c4 #1 SMP PREEMPT Thu Oct 10 15:09:40 UTC 2024 aarch64 GNU/Linux
root@jetson-agx-orin-devkit:~# hostnamectl 
[   72.942949] audit: type=1334 audit(1730133461.861:25): prog-id=22 op=UNLOAD
[   72.942966] audit: type=1334 audit(1730133461.861:26): prog-id=21 op=UNLOAD
[   72.945237] audit: type=1334 audit(1730133461.865:27): prog-id=25 op=LOAD
[   72.945847] audit: type=1334 audit(1730133461.865:28): prog-id=26 op=LOAD
[   72.946385] audit: type=1334 audit(1730133461.865:29): prog-id=27 op=LOAD
Static hostname: jetson-agx-orin-devkit
Icon name: computer
Machine ID: cf2f62141c0f4102bc3b0abbe538ab92
Boot ID: …
```
> tegra-helper-scripts: bring back FSIFW to the BINSARGS variable

- conf/machine/p3768-0000-p3767-0003.conf
Note, this is different than the SOM in the orin nano developer kit.
> Add ORIN Nano 0003 som machine configuration

- conf/machine/include/tegra-common.inc
- recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra-flash-helper.sh
Fixes #1889 
Also noticed another mostly-harmless typo in the tegra-common machine config file, which is fixed here, too.
> Helper script typo fix
